//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.09 at 06:26:11 PM IST 
//

package com.ge.trans.rmd.services.solutions.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for custLookupResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="custLookupResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="famPrivilege" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * 		   &lt;element name="metricsPrivilege" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * 		   &lt;element name="rxEmailCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * 		   &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "custLookupResponseType", propOrder = {
    "customerId",
    "famPrivilege",
    "metricsPrivilege",
    "rxEmailCheck",
    "dateFormat",
    "configAlertFlg",
    "flagMPData"
})
@XmlRootElement
public class CustLookupResponseType {

    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected String famPrivilege;
    @XmlElement(required = true)
    protected String metricsPrivilege;
    @XmlElement(required = true)
    protected String rxEmailCheck;
	protected String dateFormat;
	protected String configAlertFlg;
	protected String flagMPData;
	
    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    /**
     * Gets the value of the rxEmailCheck property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRxEmailCheck() {
        return rxEmailCheck;
    }

    /**
     * Sets the value of the rxEmailCheck property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRxEmailCheck(String rxEmailCheck) {
        this.rxEmailCheck = rxEmailCheck;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(final String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the famPrivilege property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFamPrivilege() {
        return famPrivilege;
    }

    /**
     * Sets the value of the famPrivilege property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFamPrivilege(final String value) {
        this.famPrivilege = value;
    }

    /**
     * Gets the value of the metricsPrivilege property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMetricsPrivilege() {
        return metricsPrivilege;
    }

    /**
     * Sets the value of the metricsPrivilege property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMetricsPrivilege(final String value) {
        this.metricsPrivilege = value;
    }
	public String getConfigAlertFlg() {
		return configAlertFlg;
	}
	public void setConfigAlertFlg(String configAlertFlg) {
		this.configAlertFlg = configAlertFlg;
	}

	public String getFlagMPData() {
		return flagMPData;
	}

	public void setFlagMPData(String flagMPData) {
		this.flagMPData = flagMPData;
	}
    
}
