//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 05:07:49 PM IST 
//

package com.ge.trans.rmd.services.solutions.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for solutionHistoryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="solutionHistoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="versionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="revisionHistory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orginalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solutionHistoryType", propOrder = { "versionNumber", "creationDate", "createdBy", "revisionHistory",
        "solutionId", "orginalId", "active","changeDetail"})
@XmlRootElement
public class SolutionHistoryType {

    @XmlElement(required = true)
    protected String versionNumber;
    @XmlElement(required = true)    
    protected String creationDate;
    @XmlElement(required = true)
    protected String createdBy;
    @XmlElement(required = true)
    protected String revisionHistory;
    @XmlElement(required = true)
    protected String solutionId;
    @XmlElement(required = true)
    protected String orginalId;
    @XmlElement(required = true)
    protected String active;
    @XmlElement(required = true)
    protected String changeDetail;

    public String getChangeDetail() {
		return changeDetail;
	}

	public void setChangeDetail(String changeDetail) {
		this.changeDetail = changeDetail;
	}

	/**
     * Gets the value of the versionNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersionNumber(String value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the revisionHistory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRevisionHistory() {
        return revisionHistory;
    }

    /**
     * Sets the value of the revisionHistory property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRevisionHistory(String value) {
        this.revisionHistory = value;
    }

    /**
     * Gets the value of the solutionId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionId() {
        return solutionId;
    }

    /**
     * Sets the value of the solutionId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionId(String value) {
        this.solutionId = value;
    }

    /**
     * Gets the value of the orginalId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOrginalId() {
        return orginalId;
    }

    /**
     * Sets the value of the orginalId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOrginalId(String value) {
        this.orginalId = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setActive(String value) {
        this.active = value;
    }

}
