//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.12 at 05:58:00 PM GMT+05:30 
//

package com.ge.trans.rmd.services.solutions.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for urgencyResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="urgencyResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="worstUrgency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "urgencyResponseType", propOrder = { "assetNumber", "assetGroupName", "customerId", "worstUrgency" })
@XmlRootElement
public class UrgencyResponseType {

    @XmlElement(required = true)
    protected String assetNumber;
    @XmlElement(required = true)
    protected String assetGroupName;
    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected String worstUrgency;

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the assetGroupName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetGroupName() {
        return assetGroupName;
    }

    /**
     * Sets the value of the assetGroupName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetGroupName(String value) {
        this.assetGroupName = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the worstUrgency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWorstUrgency() {
        return worstUrgency;
    }

    /**
     * Sets the value of the worstUrgency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWorstUrgency(String value) {
        this.worstUrgency = value;
    }

}
