//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.26 at 04:01:13 PM IST 
//

package com.ge.trans.rmd.services.monitoring.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for locoDashboardResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="locoDashboardResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qtrUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastKeepAlive" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="minutesLastping" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastIncidentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="minutesLastIncident" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastToolRunDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="minutesLastToolRun" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manualUserNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contactRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pingBGColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionBGColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pingBGInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionBGInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locoDashboardResponseType", propOrder = { "assetNumber", "qtrUnit", "lastKeepAlive", "minutesLastping",
        "lastIncidentDate", "minutesLastIncident", "lastToolRunDate", "minutesLastToolRun", "solutionStatus", "caseID",
        "manualUserNotes", "contactRole", "pingBGColor", "solutionBGColor", "pingBGInd", "solutionBGInd" })
@XmlRootElement
public class LocoDashboardResponseType {

    @XmlElement(required = true)
    protected String assetNumber;
    @XmlElement(required = true)
    protected String qtrUnit;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastKeepAlive;
    @XmlElement(required = true)
    protected String minutesLastping;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastIncidentDate;
    @XmlElement(required = true)
    protected String minutesLastIncident;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastToolRunDate;
    @XmlElement(required = true)
    protected String minutesLastToolRun;
    @XmlElement(required = true)
    protected String solutionStatus;
    @XmlElement(required = true)
    protected String caseID;
    protected String manualUserNotes;
    @XmlElement(required = true)
    protected String contactRole;
    @XmlElement(required = true)
    protected String pingBGColor;
    @XmlElement(required = true)
    protected String solutionBGColor;
    @XmlElement(required = true)
    protected String pingBGInd;
    @XmlElement(required = true)
    protected String solutionBGInd;

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the qtrUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQtrUnit() {
        return qtrUnit;
    }

    /**
     * Sets the value of the qtrUnit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQtrUnit(String value) {
        this.qtrUnit = value;
    }

    /**
     * Gets the value of the lastKeepAlive property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastKeepAlive() {
        return lastKeepAlive;
    }

    /**
     * Sets the value of the lastKeepAlive property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastKeepAlive(XMLGregorianCalendar value) {
        this.lastKeepAlive = value;
    }

    /**
     * Gets the value of the minutesLastping property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinutesLastping() {
        return minutesLastping;
    }

    /**
     * Sets the value of the minutesLastping property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMinutesLastping(String value) {
        this.minutesLastping = value;
    }

    /**
     * Gets the value of the lastIncidentDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastIncidentDate() {
        return lastIncidentDate;
    }

    /**
     * Sets the value of the lastIncidentDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastIncidentDate(XMLGregorianCalendar value) {
        this.lastIncidentDate = value;
    }

    /**
     * Gets the value of the minutesLastIncident property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinutesLastIncident() {
        return minutesLastIncident;
    }

    /**
     * Sets the value of the minutesLastIncident property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMinutesLastIncident(String value) {
        this.minutesLastIncident = value;
    }

    /**
     * Gets the value of the lastToolRunDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastToolRunDate() {
        return lastToolRunDate;
    }

    /**
     * Sets the value of the lastToolRunDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastToolRunDate(XMLGregorianCalendar value) {
        this.lastToolRunDate = value;
    }

    /**
     * Gets the value of the minutesLastToolRun property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinutesLastToolRun() {
        return minutesLastToolRun;
    }

    /**
     * Sets the value of the minutesLastToolRun property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMinutesLastToolRun(String value) {
        this.minutesLastToolRun = value;
    }

    /**
     * Gets the value of the solutionStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionStatus() {
        return solutionStatus;
    }

    /**
     * Sets the value of the solutionStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionStatus(String value) {
        this.solutionStatus = value;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseID(String value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the manualUserNotes property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManualUserNotes() {
        return manualUserNotes;
    }

    /**
     * Sets the value of the manualUserNotes property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setManualUserNotes(String value) {
        this.manualUserNotes = value;
    }

    /**
     * Gets the value of the contactRole property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getContactRole() {
        return contactRole;
    }

    /**
     * Sets the value of the contactRole property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setContactRole(String value) {
        this.contactRole = value;
    }

    /**
     * Gets the value of the pingBGColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPingBGColor() {
        return pingBGColor;
    }

    /**
     * Sets the value of the pingBGColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPingBGColor(String value) {
        this.pingBGColor = value;
    }

    /**
     * Gets the value of the solutionBGColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionBGColor() {
        return solutionBGColor;
    }

    /**
     * Sets the value of the solutionBGColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionBGColor(String value) {
        this.solutionBGColor = value;
    }

    /**
     * Gets the value of the pingBGInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPingBGInd() {
        return pingBGInd;
    }

    /**
     * Sets the value of the pingBGInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPingBGInd(String value) {
        this.pingBGInd = value;
    }

    /**
     * Gets the value of the solutionBGInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionBGInd() {
        return solutionBGInd;
    }

    /**
     * Sets the value of the solutionBGInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionBGInd(String value) {
        this.solutionBGInd = value;
    }

}
