//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.27 at 04:28:51 PM IST 
//

package com.ge.trans.rmd.services.monitoring.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for systemDashboardResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="systemDashboardResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mtsReceiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mtsSenderColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mtsReceiverColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mtsSender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastMsgRecvColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastSuccToolRunColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastFailToolRunColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastCaseCreatedColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mtsSenderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="mtsReceiverDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastMsgRecvdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastSuccToolRunDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastFailToolRunDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastCaseCreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="mtsSenderInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mtsReceiverInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastMsgRecvInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastSuccToolRunInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastFailToolRunInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastCaseCreatedInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "systemDashboardResponseType", propOrder = { "mtsReceiver", "mtsSenderColor", "mtsReceiverColor",
        "mtsSender", "lastMsgRecvColor", "lastSuccToolRunColor", "lastFailToolRunColor", "lastCaseCreatedColor",
        "mtsSenderDate", "mtsReceiverDate", "lastMsgRecvdDate", "lastSuccToolRunDate", "lastFailToolRunDate",
        "lastCaseCreatedDate", "mtsSenderInd", "mtsReceiverInd", "lastMsgRecvInd", "lastSuccToolRunInd",
        "lastFailToolRunInd", "lastCaseCreatedInd" })
@XmlRootElement
public class SystemDashboardResponseType {

    @XmlElement(required = true)
    protected String mtsReceiver;
    @XmlElement(required = true)
    protected String mtsSenderColor;
    @XmlElement(required = true)
    protected String mtsReceiverColor;
    @XmlElement(required = true)
    protected String mtsSender;
    @XmlElement(required = true)
    protected String lastMsgRecvColor;
    @XmlElement(required = true)
    protected String lastSuccToolRunColor;
    @XmlElement(required = true)
    protected String lastFailToolRunColor;
    @XmlElement(required = true)
    protected String lastCaseCreatedColor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mtsSenderDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mtsReceiverDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastMsgRecvdDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastSuccToolRunDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastFailToolRunDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastCaseCreatedDate;
    @XmlElement(required = true)
    protected String mtsSenderInd;
    @XmlElement(required = true)
    protected String mtsReceiverInd;
    @XmlElement(required = true)
    protected String lastMsgRecvInd;
    @XmlElement(required = true)
    protected String lastSuccToolRunInd;
    @XmlElement(required = true)
    protected String lastFailToolRunInd;
    @XmlElement(required = true)
    protected String lastCaseCreatedInd;

    /**
     * Gets the value of the mtsReceiver property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsReceiver() {
        return mtsReceiver;
    }

    /**
     * Sets the value of the mtsReceiver property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsReceiver(String value) {
        this.mtsReceiver = value;
    }

    /**
     * Gets the value of the mtsSenderColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsSenderColor() {
        return mtsSenderColor;
    }

    /**
     * Sets the value of the mtsSenderColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsSenderColor(String value) {
        this.mtsSenderColor = value;
    }

    /**
     * Gets the value of the mtsReceiverColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsReceiverColor() {
        return mtsReceiverColor;
    }

    /**
     * Sets the value of the mtsReceiverColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsReceiverColor(String value) {
        this.mtsReceiverColor = value;
    }

    /**
     * Gets the value of the mtsSender property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsSender() {
        return mtsSender;
    }

    /**
     * Sets the value of the mtsSender property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsSender(String value) {
        this.mtsSender = value;
    }

    /**
     * Gets the value of the lastMsgRecvColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastMsgRecvColor() {
        return lastMsgRecvColor;
    }

    /**
     * Sets the value of the lastMsgRecvColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastMsgRecvColor(String value) {
        this.lastMsgRecvColor = value;
    }

    /**
     * Gets the value of the lastSuccToolRunColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastSuccToolRunColor() {
        return lastSuccToolRunColor;
    }

    /**
     * Sets the value of the lastSuccToolRunColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastSuccToolRunColor(String value) {
        this.lastSuccToolRunColor = value;
    }

    /**
     * Gets the value of the lastFailToolRunColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastFailToolRunColor() {
        return lastFailToolRunColor;
    }

    /**
     * Sets the value of the lastFailToolRunColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastFailToolRunColor(String value) {
        this.lastFailToolRunColor = value;
    }

    /**
     * Gets the value of the lastCaseCreatedColor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastCaseCreatedColor() {
        return lastCaseCreatedColor;
    }

    /**
     * Sets the value of the lastCaseCreatedColor property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastCaseCreatedColor(String value) {
        this.lastCaseCreatedColor = value;
    }

    /**
     * Gets the value of the mtsSenderDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getMtsSenderDate() {
        return mtsSenderDate;
    }

    /**
     * Sets the value of the mtsSenderDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setMtsSenderDate(XMLGregorianCalendar value) {
        this.mtsSenderDate = value;
    }

    /**
     * Gets the value of the mtsReceiverDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getMtsReceiverDate() {
        return mtsReceiverDate;
    }

    /**
     * Sets the value of the mtsReceiverDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setMtsReceiverDate(XMLGregorianCalendar value) {
        this.mtsReceiverDate = value;
    }

    /**
     * Gets the value of the lastMsgRecvdDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastMsgRecvdDate() {
        return lastMsgRecvdDate;
    }

    /**
     * Sets the value of the lastMsgRecvdDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastMsgRecvdDate(XMLGregorianCalendar value) {
        this.lastMsgRecvdDate = value;
    }

    /**
     * Gets the value of the lastSuccToolRunDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastSuccToolRunDate() {
        return lastSuccToolRunDate;
    }

    /**
     * Sets the value of the lastSuccToolRunDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastSuccToolRunDate(XMLGregorianCalendar value) {
        this.lastSuccToolRunDate = value;
    }

    /**
     * Gets the value of the lastFailToolRunDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastFailToolRunDate() {
        return lastFailToolRunDate;
    }

    /**
     * Sets the value of the lastFailToolRunDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastFailToolRunDate(XMLGregorianCalendar value) {
        this.lastFailToolRunDate = value;
    }

    /**
     * Gets the value of the lastCaseCreatedDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastCaseCreatedDate() {
        return lastCaseCreatedDate;
    }

    /**
     * Sets the value of the lastCaseCreatedDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastCaseCreatedDate(XMLGregorianCalendar value) {
        this.lastCaseCreatedDate = value;
    }

    /**
     * Gets the value of the mtsSenderInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsSenderInd() {
        return mtsSenderInd;
    }

    /**
     * Sets the value of the mtsSenderInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsSenderInd(String value) {
        this.mtsSenderInd = value;
    }

    /**
     * Gets the value of the mtsReceiverInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMtsReceiverInd() {
        return mtsReceiverInd;
    }

    /**
     * Sets the value of the mtsReceiverInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMtsReceiverInd(String value) {
        this.mtsReceiverInd = value;
    }

    /**
     * Gets the value of the lastMsgRecvInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastMsgRecvInd() {
        return lastMsgRecvInd;
    }

    /**
     * Sets the value of the lastMsgRecvInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastMsgRecvInd(String value) {
        this.lastMsgRecvInd = value;
    }

    /**
     * Gets the value of the lastSuccToolRunInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastSuccToolRunInd() {
        return lastSuccToolRunInd;
    }

    /**
     * Sets the value of the lastSuccToolRunInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastSuccToolRunInd(String value) {
        this.lastSuccToolRunInd = value;
    }

    /**
     * Gets the value of the lastFailToolRunInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastFailToolRunInd() {
        return lastFailToolRunInd;
    }

    /**
     * Sets the value of the lastFailToolRunInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastFailToolRunInd(String value) {
        this.lastFailToolRunInd = value;
    }

    /**
     * Gets the value of the lastCaseCreatedInd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastCaseCreatedInd() {
        return lastCaseCreatedInd;
    }

    /**
     * Sets the value of the lastCaseCreatedInd property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastCaseCreatedInd(String value) {
        this.lastCaseCreatedInd = value;
    }

}
