//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 06:19:01 PM IST 
//

package com.ge.trans.pp.services.notification.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ppAssetServiceStatusResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ppAssetServiceStatusResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}ppAssetServiceStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ppAssetServiceStatusResponseType", propOrder = { "ppAssetServiceStatus" })
@XmlRootElement
public class PpAssetServiceStatusResponseType {

    @XmlElement(required = true)
    protected AssetServiceStatusEnum ppAssetServiceStatus;

    /**
     * Gets the value of the ppAssetServiceStatus property.
     * 
     * @return possible object is {@link AssetServiceStatusEnum }
     * 
     */
    public AssetServiceStatusEnum getPpAssetServiceStatus() {
        return ppAssetServiceStatus;
    }

    /**
     * Sets the value of the ppAssetServiceStatus property.
     * 
     * @param value
     *            allowed object is {@link AssetServiceStatusEnum }
     * 
     */
    public void setPpAssetServiceStatus(AssetServiceStatusEnum value) {
        this.ppAssetServiceStatus = value;
    }

}
