//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 11:52:52 AM IST 
//

package com.ge.trans.pp.services.notification.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ppNotificationRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ppNotificationRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}customerId"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}roadInitialName" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}roadNo" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}fromDate"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}toDate"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}notificationType" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}inactiveNotification"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}region"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}timeZone"/>
 *         &lt;element ref="{http://omd/omdservices/ppnotification}productNames" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ppNotificationRequestType", propOrder = { "customerId", "roadInitialName", "roadNo", "fromDate",
        "toDate", "notificationType", "inactiveNotification", "region", "timeZone", "productNames","userTimeZone" })
@XmlRootElement
public class PpNotificationRequestType {

    @XmlElement(required = true)
    protected String customerId;
    protected String roadInitialName;
    protected String roadNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String fromDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String toDate;
    protected String notificationType;
    protected boolean inactiveNotification;
    @XmlElement(required = true)
    protected String region;
    @XmlElement(required = true)
    protected String timeZone;
    protected List<String> productNames;
    protected String userTimeZone;

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the roadInitialName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoadInitialName() {
        return roadInitialName;
    }

    /**
     * Sets the value of the roadInitialName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoadInitialName(String value) {
        this.roadInitialName = value;
    }

    /**
     * Gets the value of the roadNo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoadNo() {
        return roadNo;
    }

    /**
     * Sets the value of the roadNo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoadNo(String value) {
        this.roadNo = value;
    }

    /**
     * Gets the value of the notificationType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNotificationType(String value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the inactiveNotification property.
     * 
     */
    public boolean isInactiveNotification() {
        return inactiveNotification;
    }

    /**
     * Sets the value of the inactiveNotification property.
     * 
     */
    public void setInactiveNotification(boolean value) {
        this.inactiveNotification = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the productNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the productNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getProductNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getProductNames() {
        if (productNames == null) {
            productNames = new ArrayList<String>();
        }
        return this.productNames;
    }

    public void setProductNames(List<String> productNames) {
        this.productNames = productNames;
    }

	public String getUserTimeZone() {
		return userTimeZone;
	}

	public void setUserTimeZone(String userTimeZone) {
		this.userTimeZone = userTimeZone;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getFromDate() {
		return fromDate;
	}

	public String getToDate() {
		return toDate;
	}

}
