//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.03 at 04:25:35 PM IST 
//

package com.ge.trans.rmd.services.kep.ruletester.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for dataFilterDetailsResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dataFilterDetailsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="func" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataFilterDetailsResponseType", propOrder = { "dataName", "value1", "value2", "func" })
@XmlRootElement
public class DataFilterDetailsResponseType {

    @XmlElement(required = true)
    protected String dataName;
    @XmlElement(required = true)
    protected String value1;
    @XmlElement(required = true)
    protected String value2;
    @XmlElement(required = true)
    protected String func;

    /**
     * Gets the value of the dataName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * Sets the value of the dataName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDataName(String value) {
        this.dataName = value;
    }

    /**
     * Gets the value of the value1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue1() {
        return value1;
    }

    /**
     * Sets the value of the value1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue1(String value) {
        this.value1 = value;
    }

    /**
     * Gets the value of the value2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue2() {
        return value2;
    }

    /**
     * Sets the value of the value2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue2(String value) {
        this.value2 = value;
    }

    /**
     * Gets the value of the func property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFunc() {
        return func;
    }

    /**
     * Sets the value of the func property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFunc(String value) {
        this.func = value;
    }

}
