//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:24:52 PM IST 
//

package com.ge.trans.rmd.services.kep.ruletester.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ruleTesterCriteriaResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ruleTesterCriteriaResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="failureType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fleet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="config" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="segmentWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classificationWindow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classifyStepSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="progExclude" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coveragePercent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="falseAlarms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="falseAlarmPercent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testerResult" type="{http://omd/omdservices/ruleservice}testerResultResponseType" maxOccurs="unbounded"/>
 *         &lt;element name="DataFilterDetails" type="{http://omd/omdservices/ruleservice}dataFilterDetailsResponseType" maxOccurs="unbounded"/>
 *         &lt;element name="testerSummary" type="{http://omd/omdservices/ruleservice}testerSummaryResponseType" maxOccurs="unbounded"/>
 *         &lt;element name="hasClassification" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rootCause" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="symptom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleTesterStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleTesterEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleTesterCriteriaResponseType", propOrder = { "customer", "failureType", "assetNumber", "fleet",
        "model", "config", "dateRange", "options", "ruleId", "segmentWindow", "classificationWindow",
        "classifyStepSize", "progExclude", "coverage", "coveragePercent", "falseAlarms", "falseAlarmPercent",
        "classification", "testerResult", "dataFilterDetails", "testerSummary", "hasClassification", "rootCause",
        "symptom", "ruleTesterStartDate", "ruleTesterEndDate", "rxDesc", "roadNumber" })
@XmlRootElement
public class RuleTesterCriteriaResponseType {

    @XmlElement(required = true)
    protected String customer;
    @XmlElement(required = true)
    protected String failureType;
    @XmlElement(required = true)
    protected String assetNumber;
    @XmlElement(required = true)
    protected String fleet;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(required = true)
    protected String config;
    @XmlElement(required = true)
    protected String dateRange;
    @XmlElement(required = true)
    protected String options;
    @XmlElement(required = true)
    protected String ruleId;
    @XmlElement(required = true)
    protected String segmentWindow;
    @XmlElement(required = true)
    protected String classificationWindow;
    @XmlElement(required = true)
    protected String classifyStepSize;
    @XmlElement(required = true)
    protected String progExclude;
    @XmlElement(required = true)
    protected String coverage;
    @XmlElement(required = true)
    protected String coveragePercent;
    @XmlElement(required = true)
    protected String falseAlarms;
    @XmlElement(required = true)
    protected String falseAlarmPercent;
    @XmlElement(required = true)
    protected String classification;
    @XmlElement(required = true)
    protected List<TesterResultResponseType> testerResult;
    @XmlElement(name = "DataFilterDetails", required = true)
    protected List<DataFilterDetailsResponseType> dataFilterDetails;
    @XmlElement(required = true)
    protected List<TesterSummaryResponseType> testerSummary;
    protected boolean hasClassification;
    @XmlElement(required = true)
    protected String rootCause;
    @XmlElement(required = true)
    protected String symptom;
    @XmlElement(required = true)
    protected String ruleTesterStartDate;
    @XmlElement(required = true)
    protected String ruleTesterEndDate;
    @XmlElement(required = true)
    protected String rxDesc;
    @XmlElement(required = true)
    protected String roadNumber;

    /**
     * Gets the value of the customer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the failureType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFailureType() {
        return failureType;
    }

    /**
     * Sets the value of the failureType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFailureType(String value) {
        this.failureType = value;
    }

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the fleet property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFleet() {
        return fleet;
    }

    /**
     * Sets the value of the fleet property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFleet(String value) {
        this.fleet = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the config property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConfig(String value) {
        this.config = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDateRange(String value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOptions(String value) {
        this.options = value;
    }

    /**
     * Gets the value of the ruleId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * Sets the value of the ruleId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleId(String value) {
        this.ruleId = value;
    }

    /**
     * Gets the value of the segmentWindow property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSegmentWindow() {
        return segmentWindow;
    }

    /**
     * Sets the value of the segmentWindow property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSegmentWindow(String value) {
        this.segmentWindow = value;
    }

    /**
     * Gets the value of the classificationWindow property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getClassificationWindow() {
        return classificationWindow;
    }

    /**
     * Sets the value of the classificationWindow property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClassificationWindow(String value) {
        this.classificationWindow = value;
    }

    /**
     * Gets the value of the classifyStepSize property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getClassifyStepSize() {
        return classifyStepSize;
    }

    /**
     * Sets the value of the classifyStepSize property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClassifyStepSize(String value) {
        this.classifyStepSize = value;
    }

    /**
     * Gets the value of the progExclude property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProgExclude() {
        return progExclude;
    }

    /**
     * Sets the value of the progExclude property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProgExclude(String value) {
        this.progExclude = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the coveragePercent property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCoveragePercent() {
        return coveragePercent;
    }

    /**
     * Sets the value of the coveragePercent property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCoveragePercent(String value) {
        this.coveragePercent = value;
    }

    /**
     * Gets the value of the falseAlarms property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFalseAlarms() {
        return falseAlarms;
    }

    /**
     * Sets the value of the falseAlarms property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFalseAlarms(String value) {
        this.falseAlarms = value;
    }

    /**
     * Gets the value of the falseAlarmPercent property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFalseAlarmPercent() {
        return falseAlarmPercent;
    }

    /**
     * Sets the value of the falseAlarmPercent property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFalseAlarmPercent(String value) {
        this.falseAlarmPercent = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the testerResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the testerResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTesterResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TesterResultResponseType }
     * 
     * 
     */
    public List<TesterResultResponseType> getTesterResult() {
        if (testerResult == null) {
            testerResult = new ArrayList<TesterResultResponseType>();
        }
        return this.testerResult;
    }

    /**
     * Gets the value of the dataFilterDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the dataFilterDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDataFilterDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataFilterDetailsResponseType }
     * 
     * 
     */
    public List<DataFilterDetailsResponseType> getDataFilterDetails() {
        if (dataFilterDetails == null) {
            dataFilterDetails = new ArrayList<DataFilterDetailsResponseType>();
        }
        return this.dataFilterDetails;
    }

    /**
     * Gets the value of the testerSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the testerSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTesterSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TesterSummaryResponseType }
     * 
     * 
     */
    public List<TesterSummaryResponseType> getTesterSummary() {
        if (testerSummary == null) {
            testerSummary = new ArrayList<TesterSummaryResponseType>();
        }
        return this.testerSummary;
    }

    /**
     * Gets the value of the hasClassification property.
     * 
     */
    public boolean isHasClassification() {
        return hasClassification;
    }

    /**
     * Sets the value of the hasClassification property.
     * 
     */
    public void setHasClassification(boolean value) {
        this.hasClassification = value;
    }

    /**
     * Gets the value of the rootCause property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRootCause() {
        return rootCause;
    }

    /**
     * Sets the value of the rootCause property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRootCause(String value) {
        this.rootCause = value;
    }

    /**
     * Gets the value of the symptom property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * Sets the value of the symptom property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSymptom(String value) {
        this.symptom = value;
    }

    /**
     * Gets the value of the ruleTesterStartDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleTesterStartDate() {
        return ruleTesterStartDate;
    }

    /**
     * Sets the value of the ruleTesterStartDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleTesterStartDate(String value) {
        this.ruleTesterStartDate = value;
    }

    /**
     * Gets the value of the ruleTesterEndDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleTesterEndDate() {
        return ruleTesterEndDate;
    }

    /**
     * Sets the value of the ruleTesterEndDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleTesterEndDate(String value) {
        this.ruleTesterEndDate = value;
    }

    public String getRxDesc() {
        return rxDesc;
    }

    public void setRxDesc(String rxDesc) {
        this.rxDesc = rxDesc;
    }

    public String getRoadNumber() {
        return roadNumber;
    }

    public void setRoadNumber(String roadNumber) {
        this.roadNumber = roadNumber;
    }

}
