//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 10:35:02 PM GMT+05:30 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for favFilterDetailType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="favFilterDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filterId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="filterName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="filterDetails" type="{http://omd/omdservices/adminservice}filterDetailType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "favFilterDetailType", propOrder = { "filterId", "filterName", "filterDetails" })
@XmlRootElement
public class FavFilterDetailType {

    protected Long filterId;
    protected String filterName;
    @XmlElement(required = true)
    protected List<FilterDetailType> filterDetails;

    /**
     * Gets the value of the filterId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFilterId() {
        return filterId;
    }

    /**
     * Sets the value of the filterId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setFilterId(Long value) {
        this.filterId = value;
    }

    /**
     * Gets the value of the filterName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFilterName() {
        return filterName;
    }

    /**
     * Sets the value of the filterName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFilterName(String value) {
        this.filterName = value;
    }

    /**
     * Gets the value of the filterDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the filterDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFilterDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterDetailType }
     * 
     * 
     */
    public List<FilterDetailType> getFilterDetails() {
        if (filterDetails == null) {
            filterDetails = new ArrayList<FilterDetailType>();
        }
        return this.filterDetails;
    }

    public void setFilterDetails(List<FilterDetailType> filterDetails) {
        this.filterDetails = filterDetails;
    }

}
