//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 10:35:02 PM GMT+05:30 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fetchFavFilterResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fetchFavFilterResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usrRoleSeqId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="filterDetail" type="{http://omd/omdservices/adminservice}favFilterDetailType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fetchFavFilterResponseType", propOrder = { "usrRoleSeqId", "filterDetail" })
@XmlRootElement
public class FetchFavFilterResponseType {

    protected Long usrRoleSeqId;
    @XmlElement(required = true)
    protected List<FavFilterDetailType> filterDetail;

    /**
     * Gets the value of the usrRoleSeqId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getUsrRoleSeqId() {
        return usrRoleSeqId;
    }

    /**
     * Sets the value of the usrRoleSeqId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setUsrRoleSeqId(Long value) {
        this.usrRoleSeqId = value;
    }

    /**
     * Gets the value of the filterDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the filterDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFilterDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FavFilterDetailType }
     * 
     * 
     */
    public List<FavFilterDetailType> getFilterDetail() {
        if (filterDetail == null) {
            filterDetail = new ArrayList<FavFilterDetailType>();
        }
        return this.filterDetail;
    }

    public void setFilterDetail(List<FavFilterDetailType> filterDetail) {
        this.filterDetail = filterDetail;
    }

}
