//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 10:35:02 PM GMT+05:30 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for filterDetailType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="filterDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fromFilterValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="lastUpdatedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastUpdatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="toFilterValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="usrFilterDetailId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="usrFilterId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="columnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterDetailType", propOrder = { "createdBy", "createdDate", "fromFilterValue", "lastUpdatedBy",
        "lastUpdatedDate", "toFilterValue", "usrFilterDetailId", "usrFilterId", "columnName", "columnType",
        "resourceName", "resourceId" })
@XmlRootElement
public class FilterDetailType {

    protected String createdBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    protected Object fromFilterValue;
    protected String lastUpdatedBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedDate;
    protected Object toFilterValue;
    protected Long usrFilterDetailId;
    protected Long usrFilterId;
    protected String columnName;
    protected String columnType;
    protected String resourceName;
    protected Long resourceId;

    /**
     * Gets the value of the createdBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the fromFilterValue property.
     * 
     * @return possible object is {@link Object }
     * 
     */
    public Object getFromFilterValue() {
        return fromFilterValue;
    }

    /**
     * Sets the value of the fromFilterValue property.
     * 
     * @param value
     *            allowed object is {@link Object }
     * 
     */
    public void setFromFilterValue(Object value) {
        this.fromFilterValue = value;
    }

    /**
     * Gets the value of the lastUpdatedBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets the value of the lastUpdatedBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastUpdatedBy(String value) {
        this.lastUpdatedBy = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

    /**
     * Gets the value of the toFilterValue property.
     * 
     * @return possible object is {@link Object }
     * 
     */
    public Object getToFilterValue() {
        return toFilterValue;
    }

    /**
     * Sets the value of the toFilterValue property.
     * 
     * @param value
     *            allowed object is {@link Object }
     * 
     */
    public void setToFilterValue(Object value) {
        this.toFilterValue = value;
    }

    /**
     * Gets the value of the usrFilterDetailId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getUsrFilterDetailId() {
        return usrFilterDetailId;
    }

    /**
     * Sets the value of the usrFilterDetailId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setUsrFilterDetailId(Long value) {
        this.usrFilterDetailId = value;
    }

    /**
     * Gets the value of the usrFilterId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getUsrFilterId() {
        return usrFilterId;
    }

    /**
     * Sets the value of the usrFilterId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setUsrFilterId(Long value) {
        this.usrFilterId = value;
    }

    /**
     * Gets the value of the columnName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnName(String value) {
        this.columnName = value;
    }

    /**
     * Gets the value of the columnType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * Sets the value of the columnType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnType(String value) {
        this.columnType = value;
    }

    /**
     * Gets the value of the resourceName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setResourceName(String value) {
        this.resourceName = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setResourceId(Long value) {
        this.resourceId = value;
    }

}
