//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 03:23:54 PM IST 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for locationResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="locationResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addressDetail" type="{http://omd/omdservices/adminservice}addressDetailType"/>
 *         &lt;element name="includeInactive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationResponseType", propOrder = { "locationId", "locationType", "locationName", "addressDetail",
        "includeInactive" })
@XmlRootElement
public class LocationResponseType {

    @XmlElement(required = true)
    protected String locationId;
    @XmlElement(required = true)
    protected String locationType;
    @XmlElement(required = true)
    protected String locationName;
    @XmlElement(required = true)
    protected AddressDetailType addressDetail;
    @XmlElement(required = true)
    protected String includeInactive;

    /**
     * Gets the value of the locationId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the locationType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocationType() {
        return locationType;
    }

    /**
     * Sets the value of the locationType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocationType(String value) {
        this.locationType = value;
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLocationName(String value) {
        this.locationName = value;
    }

    /**
     * Gets the value of the addressDetail property.
     * 
     * @return possible object is {@link AddressDetailType }
     * 
     */
    public AddressDetailType getAddressDetail() {
        return addressDetail;
    }

    /**
     * Sets the value of the addressDetail property.
     * 
     * @param value
     *            allowed object is {@link AddressDetailType }
     * 
     */
    public void setAddressDetail(AddressDetailType value) {
        this.addressDetail = value;
    }

    /**
     * Gets the value of the includeInactive property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIncludeInactive() {
        return includeInactive;
    }

    /**
     * Sets the value of the includeInactive property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIncludeInactive(String value) {
        this.includeInactive = value;
    }

}
