//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 08:45:44 PM IST 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SaveFavFilterType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SaveFavFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filterId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linkUsrRoleSeqId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnInfo" type="{http://omd/omdservices/adminservice}columnInfoType" minOccurs="0"/>
 *         &lt;element name="dataInfo" type="{http://omd/omdservices/adminservice}dataInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveFavFilterType", propOrder = { "filterId", "linkUsrRoleSeqId", "screenName", "columnInfo",
        "dataInfo" })
@XmlRootElement
public class SaveFavFilterType {

    protected String filterId;
    protected String linkUsrRoleSeqId;
    @XmlElement(required = true)
    protected String screenName;
    protected ColumnInfoType columnInfo;
    protected DataInfoType dataInfo;

    /**
     * Gets the value of the filterId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFilterId() {
        return filterId;
    }

    /**
     * Sets the value of the filterId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFilterId(String value) {
        this.filterId = value;
    }

    /**
     * Gets the value of the linkUsrRoleSeqId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLinkUsrRoleSeqId() {
        return linkUsrRoleSeqId;
    }

    /**
     * Sets the value of the linkUsrRoleSeqId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLinkUsrRoleSeqId(String value) {
        this.linkUsrRoleSeqId = value;
    }

    /**
     * Gets the value of the screenName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * Sets the value of the screenName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setScreenName(String value) {
        this.screenName = value;
    }

    /**
     * Gets the value of the columnInfo property.
     * 
     * @return possible object is {@link ColumnInfoType }
     * 
     */
    public ColumnInfoType getColumnInfo() {
        return columnInfo;
    }

    /**
     * Sets the value of the columnInfo property.
     * 
     * @param value
     *            allowed object is {@link ColumnInfoType }
     * 
     */
    public void setColumnInfo(ColumnInfoType value) {
        this.columnInfo = value;
    }

    /**
     * Gets the value of the dataInfo property.
     * 
     * @return possible object is {@link DataInfoType }
     * 
     */
    public DataInfoType getDataInfo() {
        return dataInfo;
    }

    /**
     * Sets the value of the dataInfo property.
     * 
     * @param value
     *            allowed object is {@link DataInfoType }
     * 
     */
    public void setDataInfo(DataInfoType value) {
        this.dataInfo = value;
    }

}
