//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.29 at 08:26:38 PM IST 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for userDetailType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="userDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userSeqId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="homePage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listCustomerIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="strLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="oldUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="newUserIdEntered" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="userType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userDetailType", propOrder = { "userName", "userSeqId", "userId", "status", "homePage", "password",
        "customerId", "customerName", "listCustomerIds", "strLanguage", "oldUserId", "newUserIdEntered", "userType",
        "lastUpdatedBy","lastUpdatedTime","mobileAccess","endUserScoring" })
@XmlRootElement
public class UserDetailType {

    public void setListCustomerIds(List<String> listCustomerIds) {
        this.listCustomerIds = listCustomerIds;
    }

    @XmlElement(required = true)
    protected String userName;
    protected long userSeqId;
    @XmlElement(required = true)
    protected String userId;
    protected String status;
    protected String homePage;
    protected String password;
    protected String customerId;
    protected String customerName;
    @XmlElement(required = true)
    protected List<String> listCustomerIds;
    protected String strLanguage;
    @XmlElement(required = true)
    protected String oldUserId;
    protected String newUserIdEntered;
    protected String userType;
    
  //newly added code
    protected String lastUpdatedBy;
    protected String lastUpdatedTime;
    //Added by Murali Medicherla for Rally Id : US226051
    protected String mobileAccess;
    protected String endUserScoring;

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getOldUserId() {
        return oldUserId;
    }

    public void setOldUserId(String oldUserId) {
        this.oldUserId = oldUserId;
    }

    public String getStrLanguage() {
        return strLanguage;
    }

    public void setStrLanguage(String strLanguage) {
        this.strLanguage = strLanguage;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the userSeqId property.
     * 
     */
    public long getUserSeqId() {
        return userSeqId;
    }

    /**
     * Sets the value of the userSeqId property.
     * 
     */
    public void setUserSeqId(long value) {
        this.userSeqId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the homePage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHomePage() {
        return homePage;
    }

    /**
     * Sets the value of the homePage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setHomePage(String value) {
        this.homePage = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the listCustomerIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the listCustomerIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getListCustomerIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getListCustomerIds() {
        if (listCustomerIds == null) {
            listCustomerIds = new ArrayList<String>();
        }
        return this.listCustomerIds;
    }

    /**
     * Gets the value of the newUserIdEntered property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNewUserIdEntered() {
        return newUserIdEntered;
    }

    /**
     * Sets the value of the newUserIdEntered property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNewUserIdEntered(String value) {
        this.newUserIdEntered = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
  //newly added code
  	public String getLastUpdatedBy() {
  		return lastUpdatedBy;
  	}

  	public void setLastUpdatedBy(String lastUpdatedBy) {
  		this.lastUpdatedBy = lastUpdatedBy;
  	}

  	public String getLastUpdatedTime() {
  		return lastUpdatedTime;
  	}

  	public void setLastUpdatedTime(String lastUpdatedTime) {
  		this.lastUpdatedTime = lastUpdatedTime;
  	}

	public String getMobileAccess() {
		return mobileAccess;
	}

	public void setMobileAccess(String mobileAccess) {
		this.mobileAccess = mobileAccess;
	}

	public String getEndUserScoring() {
		return endUserScoring;
	}

	public void setEndUserScoring(String endUserScoring) {
		this.endUserScoring = endUserScoring;
	}
	
	
}
