//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.25 at 08:45:48 AM IST 
//

package com.ge.trans.rmd.services.admin.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for usersResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="usersResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userDetail" type="{http://omd/omdservices/adminservice}userDetailType"/>
 *         &lt;element name="personalDetail" type="{http://omd/omdservices/adminservice}personalDetailType"/>
 *         &lt;element name="timeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roles" type="{http://omd/omdservices/adminservice}roleType" minOccurs="0"/>
 *         &lt;element name="defaultRole" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rolesDetail" type="{http://omd/omdservices/adminservice}RolesType" maxOccurs="unbounded"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passwordChangeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lastLoginDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "usersResponseType", propOrder = { "userDetail", "personalDetail", "timeZone", "roles", "defaultRole",
        "rolesDetail", "language", "customerId", "passwordChangeDate", "lastLoginDate","uom" })
@XmlRootElement
public class UsersResponseType {

    @XmlElement(required = true)
    protected UserDetailType userDetail;
    @XmlElement(required = true)
    protected PersonalDetailType personalDetail;
    @XmlElement(required = true)
    protected String timeZone;
    protected RoleType roles;
    protected String defaultRole;
    @XmlElement(required = true)
    protected List<RolesType> rolesDetail;
    @XmlElement(required = true)
    protected String language;
    protected String customerId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar passwordChangeDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastLoginDate;
    protected String uom;
    
    public String getUom() {
		return uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	/**
     * Gets the value of the userDetail property.
     * 
     * @return possible object is {@link UserDetailType }
     * 
     */
    public UserDetailType getUserDetail() {
        return userDetail;
    }

    /**
     * Sets the value of the userDetail property.
     * 
     * @param value
     *            allowed object is {@link UserDetailType }
     * 
     */
    public void setUserDetail(UserDetailType value) {
        this.userDetail = value;
    }

    /**
     * Gets the value of the personalDetail property.
     * 
     * @return possible object is {@link PersonalDetailType }
     * 
     */
    public PersonalDetailType getPersonalDetail() {
        return personalDetail;
    }

    /**
     * Sets the value of the personalDetail property.
     * 
     * @param value
     *            allowed object is {@link PersonalDetailType }
     * 
     */
    public void setPersonalDetail(PersonalDetailType value) {
        this.personalDetail = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return possible object is {@link RoleType }
     * 
     */
    public RoleType getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *            allowed object is {@link RoleType }
     * 
     */
    public void setRoles(RoleType value) {
        this.roles = value;
    }

    /**
     * Gets the value of the defaultRole property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDefaultRole() {
        return defaultRole;
    }

    /**
     * Sets the value of the defaultRole property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDefaultRole(String value) {
        this.defaultRole = value;
    }

    /**
     * Gets the value of the rolesDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the rolesDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRolesDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RolesType
     * }
     * 
     * 
     */
    public List<RolesType> getRolesDetail() {
        if (rolesDetail == null) {
            rolesDetail = new ArrayList<RolesType>();
        }
        return this.rolesDetail;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the passwordChangeDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getPasswordChangeDate() {
        return passwordChangeDate;
    }

    /**
     * Sets the value of the passwordChangeDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setPasswordChangeDate(XMLGregorianCalendar value) {
        this.passwordChangeDate = value;
    }

    /**
     * Gets the value of the lastLoginDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * Sets the value of the lastLoginDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastLoginDate(XMLGregorianCalendar value) {
        this.lastLoginDate = value;
    }

}
