//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 11:51:39 AM IST 
//

package com.ge.trans.pp.services.proximity.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for proximityRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="proximityRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}customerId"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}cityName" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}stateCode" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}countryCode" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}latitude" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}longitude" minOccurs="0"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}rangeInMiles"/>
 *         &lt;element ref="{http://omd/omdservices/ppproximity}productNames" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proximityRequestType", propOrder = { "customerId", "cityName", "stateCode", "countryCode", "latitude",
        "longitude", "rangeInMiles", "productNames" })
@XmlRootElement
public class ProximityRequestType {

    @XmlElement(required = true)
    protected String customerId;
    protected String cityName;
    protected String stateCode;
    protected String countryCode;
    protected Integer latitude;
    protected Integer longitude;
    protected float rangeInMiles;
    protected List<String> productNames;

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the stateCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * Sets the value of the stateCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStateCode(String value) {
        this.stateCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setLatitude(Integer value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setLongitude(Integer value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the rangeInMiles property.
     * 
     */
    public float getRangeInMiles() {
        return rangeInMiles;
    }

    /**
     * Sets the value of the rangeInMiles property.
     * 
     */
    public void setRangeInMiles(float value) {
        this.rangeInMiles = value;
    }

    /**
     * Gets the value of the productNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the productNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getProductNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getProductNames() {
        if (productNames == null) {
            productNames = new ArrayList<String>();
        }
        return this.productNames;
    }

    public void setProductNames(List<String> productNames) {
        this.productNames = productNames;
    }

}
