//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 06:50:08 PM IST 
//


package com.ge.trans.rmd.services.assets.valueobjects;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assetResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assetResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assetNumberResponseType", propOrder = {
    "assetNumber",
    "customerID",
    "arlAssetNumbers",
    "model",
    "modelGeneral"
})
@XmlRootElement
public class AssetNumberResponseType {
    @XmlElement(required = true)
    protected String assetNumber;
    @XmlElement(required = true)
    protected String customerID;
	@XmlElement(required = true)
	protected List<String> arlAssetNumbers;
	@XmlElement(required = true)
	protected String model;
	protected String modelGeneral;
    public List<String> getArlAssetNumbers() {
		return arlAssetNumbers;
	}

	public void setArlAssetNumbers(List<String> arlAssetNumbers) {
		this.arlAssetNumbers = arlAssetNumbers;
	}

	public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    } 

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * @return the modelGeneral
	 */
	public String getModelGeneral() {
		return modelGeneral;
	}

	/**
	 * @param modelGeneral the modelGeneral to set
	 */
	public void setModelGeneral(String modelGeneral) {
		this.modelGeneral = modelGeneral;
	}

 

}
