//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.11 at 01:14:38 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for LastDownLoadStatusResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LastDownLoadStatusResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetNoHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lstDownloadTm" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lstDownloadHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stateHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vaxHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vaxDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="egu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eguHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eguDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="inc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="incHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="incDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="snp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="snpHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="snpDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LastDownLoadStatusResponseType", propOrder = { "custHeader", "customerHeader", "assetNumber",
        "assetNoHeader", "lstDownloadTm", "lstDownloadHeader", "state", "stateHeader", "vax", "vaxHeader", "vaxDt",
        "egu", "eguHeader", "eguDt", "inc", "incHeader", "incDt", "snp", "snpHeader", "snpDt" })
@XmlRootElement
public class LastDownLoadStatusResponseType {

    protected String custHeader;
    protected String customerHeader;
    protected String assetNumber;
    protected String assetNoHeader;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lstDownloadTm;
    protected String lstDownloadHeader;
    protected String state;
    protected String stateHeader;
    protected String vax;
    protected String vaxHeader;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vaxDt;
    protected String egu;
    protected String eguHeader;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eguDt;
    protected String inc;
    protected String incHeader;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar incDt;
    protected String snp;
    protected String snpHeader;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar snpDt;

    /**
     * Gets the value of the custHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustHeader() {
        return custHeader;
    }

    /**
     * Sets the value of the custHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustHeader(String value) {
        this.custHeader = value;
    }

    /**
     * Gets the value of the customerHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerHeader() {
        return customerHeader;
    }

    /**
     * Sets the value of the customerHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerHeader(String value) {
        this.customerHeader = value;
    }

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the assetNoHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNoHeader() {
        return assetNoHeader;
    }

    /**
     * Sets the value of the assetNoHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNoHeader(String value) {
        this.assetNoHeader = value;
    }

    /**
     * Gets the value of the lstDownloadTm property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLstDownloadTm() {
        return lstDownloadTm;
    }

    /**
     * Sets the value of the lstDownloadTm property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLstDownloadTm(XMLGregorianCalendar value) {
        this.lstDownloadTm = value;
    }

    /**
     * Gets the value of the lstDownloadHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLstDownloadHeader() {
        return lstDownloadHeader;
    }

    /**
     * Sets the value of the lstDownloadHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLstDownloadHeader(String value) {
        this.lstDownloadHeader = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the stateHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStateHeader() {
        return stateHeader;
    }

    /**
     * Sets the value of the stateHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStateHeader(String value) {
        this.stateHeader = value;
    }

    /**
     * Gets the value of the vax property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVax() {
        return vax;
    }

    /**
     * Sets the value of the vax property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVax(String value) {
        this.vax = value;
    }

    /**
     * Gets the value of the vaxHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVaxHeader() {
        return vaxHeader;
    }

    /**
     * Sets the value of the vaxHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVaxHeader(String value) {
        this.vaxHeader = value;
    }

    /**
     * Gets the value of the vaxDt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getVaxDt() {
        return vaxDt;
    }

    /**
     * Sets the value of the vaxDt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setVaxDt(XMLGregorianCalendar value) {
        this.vaxDt = value;
    }

    /**
     * Gets the value of the egu property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEgu() {
        return egu;
    }

    /**
     * Sets the value of the egu property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEgu(String value) {
        this.egu = value;
    }

    /**
     * Gets the value of the eguHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEguHeader() {
        return eguHeader;
    }

    /**
     * Sets the value of the eguHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEguHeader(String value) {
        this.eguHeader = value;
    }

    /**
     * Gets the value of the eguDt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getEguDt() {
        return eguDt;
    }

    /**
     * Sets the value of the eguDt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setEguDt(XMLGregorianCalendar value) {
        this.eguDt = value;
    }

    /**
     * Gets the value of the inc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInc() {
        return inc;
    }

    /**
     * Sets the value of the inc property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInc(String value) {
        this.inc = value;
    }

    /**
     * Gets the value of the incHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIncHeader() {
        return incHeader;
    }

    /**
     * Sets the value of the incHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIncHeader(String value) {
        this.incHeader = value;
    }

    /**
     * Gets the value of the incDt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getIncDt() {
        return incDt;
    }

    /**
     * Sets the value of the incDt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setIncDt(XMLGregorianCalendar value) {
        this.incDt = value;
    }

    /**
     * Gets the value of the snp property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSnp() {
        return snp;
    }

    /**
     * Sets the value of the snp property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSnp(String value) {
        this.snp = value;
    }

    /**
     * Gets the value of the snpHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSnpHeader() {
        return snpHeader;
    }

    /**
     * Sets the value of the snpHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSnpHeader(String value) {
        this.snpHeader = value;
    }

    /**
     * Gets the value of the snpDt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getSnpDt() {
        return snpDt;
    }

    /**
     * Sets the value of the snpDt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setSnpDt(XMLGregorianCalendar value) {
        this.snpDt = value;
    }

}
