//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.18 at 08:27:48 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for lifeStatisticsRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lifeStatisticsRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetGroupNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="controllerCfg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="toDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lifeStatisticsRequestType", propOrder = { "assetNumber", "assetGroupName", "assetGroupNumber",
        "customerID", "controllerCfg", "fromDate", "toDate","hideL3Fault" })
@XmlRootElement
public class LifeStatisticsRequestType {

    @XmlElement(required = true)
    protected String assetNumber;
    @XmlElement(required = true)
    protected String assetGroupName;
    protected long assetGroupNumber;
    @XmlElement(required = true)
    protected String customerID;
    @XmlElement(required = true)
    protected String controllerCfg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fromDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar toDate;
    protected boolean hideL3Fault;

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the assetGroupName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetGroupName() {
        return assetGroupName;
    }

    /**
     * Sets the value of the assetGroupName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetGroupName(String value) {
        this.assetGroupName = value;
    }

    /**
     * Gets the value of the assetGroupNumber property.
     * 
     */
    public long getAssetGroupNumber() {
        return assetGroupNumber;
    }

    /**
     * Sets the value of the assetGroupNumber property.
     * 
     */
    public void setAssetGroupNumber(long value) {
        this.assetGroupNumber = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the controllerCfg property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControllerCfg() {
        return controllerCfg;
    }

    /**
     * Sets the value of the controllerCfg property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setControllerCfg(String value) {
        this.controllerCfg = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

	public boolean isHideL3Fault() {
		return hideL3Fault;
	}

	public void setHideL3Fault(boolean hideL3Fault) {
		this.hideL3Fault = hideL3Fault;
	}



}
