//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.26 at 06:07:52 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.ge.trans.rmd.services.assets.valueobjects package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Model_QNAME = new QName("http://omd/omdservices/assetservice", "model");
    private final static QName _FaultDataResponse_QNAME = new QName("http://omd/omdservices/assetservice",
            "faultDataResponse");
    private final static QName _ServiceResponse_QNAME = new QName("http://omd/omdservices/assetservice",
            "serviceResponse");
    private final static QName _LastDownLoadStatusResponse_QNAME = new QName("http://omd/omdservices/assetservice",
            "LastDownLoadStatusResponse");
    private final static QName _ToolParamInfoResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "ToolParamInfoResponseType");
    private final static QName _HealthCheckRequest_QNAME = new QName("http://omd/omdservices/assetservice",
            "healthCheckRequest");
    private final static QName _FaultResponse_QNAME = new QName("http://omd/omdservices/assetservice", "faultResponse");
    private final static QName _FaultDetailsResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "FaultDetailsResponseType");
    private final static QName _AssetResponse_QNAME = new QName("http://omd/omdservices/assetservice", "assetResponse");
    private final static QName _LastFaultStatusResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "LastFaultStatusResponseType");
    private final static QName _ToolsParamGroupResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "ToolsParamGroupResponseType");
    private final static QName _RequestHistoryResponse_QNAME = new QName("http://omd/omdservices/assetservice",
            "requestHistoryResponse");
    private final static QName _VehicleCommStatusResponse_QNAME = new QName("http://omd/omdservices/assetservice",
            "vehicleCommStatusResponse");
    private final static QName _FaultLogServiceResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "faultLogServiceResponseType");
    private final static QName _FaultDataResponseType_QNAME = new QName("http://omd/omdservices/assetservice",
            "faultDataResponseType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.ge.trans.rmd.services.assets.valueobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FaultResponseType }
     * 
     */
    public FaultResponseType createFaultResponseType() {
        return new FaultResponseType();
    }

    /**
     * Create an instance of {@link Fleet }
     * 
     */
    public Fleet createFleet() {
        return new Fleet();
    }

    /**
     * Create an instance of {@link FaultDetailsResponseType }
     * 
     */
    public FaultDetailsResponseType createFaultDetailsResponseType() {
        return new FaultDetailsResponseType();
    }

    /**
     * Create an instance of {@link ToolParamInfoResponseType }
     * 
     */
    public ToolParamInfoResponseType createToolParamInfoResponseType() {
        return new ToolParamInfoResponseType();
    }

    /**
     * Create an instance of {@link HealthCheckRequestType }
     * 
     */
    public HealthCheckRequestType createHealthCheckRequestType() {
        return new HealthCheckRequestType();
    }

    /**
     * Create an instance of {@link ToolsParamGroupResponseType }
     * 
     */
    public ToolsParamGroupResponseType createToolsParamGroupResponseType() {
        return new ToolsParamGroupResponseType();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link LastDownLoadStatusResponseType }
     * 
     */
    public LastDownLoadStatusResponseType createLastDownLoadStatusResponseType() {
        return new LastDownLoadStatusResponseType();
    }

    /**
     * Create an instance of {@link FaultDataResponseType }
     * 
     */
    public FaultDataResponseType createFaultDataResponseType() {
        return new FaultDataResponseType();
    }

    /**
     * Create an instance of {@link FaultDataDetailsResponseType }
     * 
     */
    public FaultDataDetailsResponseType createFaultDataDetailsResponseType() {
        return new FaultDataDetailsResponseType();
    }

    /**
     * Create an instance of {@link VehicleCommStatusResponseType }
     * 
     */
    public VehicleCommStatusResponseType createVehicleCommStatusResponseType() {
        return new VehicleCommStatusResponseType();
    }

    /**
     * Create an instance of {@link FaultLogServiceResponseType }
     * 
     */
    public FaultLogServiceResponseType createFaultLogServiceResponseType() {
        return new FaultLogServiceResponseType();
    }

    /**
     * Create an instance of {@link LastFaultStatusResponseType }
     * 
     */
    public LastFaultStatusResponseType createLastFaultStatusResponseType() {
        return new LastFaultStatusResponseType();
    }

    /**
     * Create an instance of {@link AssetLocatorResponseType }
     * 
     */
    public AssetLocatorResponseType createAssetLocatorResponseType() {
        return new AssetLocatorResponseType();
    }

    /**
     * Create an instance of {@link HeaderInfoType }
     * 
     */
    public HeaderInfoType createHeaderInfoType() {
        return new HeaderInfoType();
    }

    /**
     * Create an instance of {@link AssetServicesResponseType }
     * 
     */
    public AssetServicesResponseType createAssetServicesResponseType() {
        return new AssetServicesResponseType();
    }

    /**
     * Create an instance of {@link AssetResponseType }
     * 
     */
    public AssetResponseType createAssetResponseType() {
        return new AssetResponseType();
    }

    /**
     * Create an instance of {@link AssetLocRequestType }
     * 
     */
    public AssetLocRequestType createAssetLocRequestType() {
        return new AssetLocRequestType();
    }

    /**
     * Create an instance of {@link CustomerAssetResponseType }
     * 
     */
    public CustomerAssetResponseType createCustomerAssetResponseType() {
        return new CustomerAssetResponseType();
    }

    /**
     * Create an instance of {@link RequestHistoryResponseType }
     * 
     */
    public RequestHistoryResponseType createRequestHistoryResponseType() {
        return new RequestHistoryResponseType();
    }

    /**
     * Create an instance of {@link FaultDetailsType }
     * 
     */
    public FaultDetailsType createFaultDetailsType() {
        return new FaultDetailsType();
    }

    /**
     * Create an instance of {@link KeepAliveHistoryType }
     * 
     */
    public KeepAliveHistoryType createKeepAliveHistoryType() {
        return new KeepAliveHistoryType();
    }

    /**
     * Create an instance of {@link ServiceResponseType }
     * 
     */
    public ServiceResponseType createServiceResponseType() {
        return new ServiceResponseType();
    }

    /**
     * Create an instance of {@link AssetsRequestType }
     * 
     */
    public AssetsRequestType createAssetsRequestType() {
        return new AssetsRequestType();
    }

    /**
     * Create an instance of {@link ParameterResponseType }
     * 
     */
    public ParameterResponseType createParameterResponseType() {
        return new ParameterResponseType();
    }

    /**
     * Create an instance of {@link ProdAssetMapRequestType }
     * 
     */
    public ProdAssetMapRequestType createProdAssetMapRequestType() {
        return new ProdAssetMapRequestType();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Model }
     * {@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "model")
    public JAXBElement<Model> createModel(Model value) {
        return new JAXBElement<Model>(_Model_QNAME, Model.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link FaultDataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "faultDataResponse")
    public JAXBElement<FaultDataResponseType> createFaultDataResponse(FaultDataResponseType value) {
        return new JAXBElement<FaultDataResponseType>(_FaultDataResponse_QNAME, FaultDataResponseType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "serviceResponse")
    public JAXBElement<ServiceResponseType> createServiceResponse(ServiceResponseType value) {
        return new JAXBElement<ServiceResponseType>(_ServiceResponse_QNAME, ServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link LastDownLoadStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "LastDownLoadStatusResponse")
    public JAXBElement<LastDownLoadStatusResponseType> createLastDownLoadStatusResponse(
            LastDownLoadStatusResponseType value) {
        return new JAXBElement<LastDownLoadStatusResponseType>(_LastDownLoadStatusResponse_QNAME,
                LastDownLoadStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ToolParamInfoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "ToolParamInfoResponseType")
    public JAXBElement<ToolParamInfoResponseType> createToolParamInfoResponseType(ToolParamInfoResponseType value) {
        return new JAXBElement<ToolParamInfoResponseType>(_ToolParamInfoResponseType_QNAME,
                ToolParamInfoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link HealthCheckRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "healthCheckRequest")
    public JAXBElement<HealthCheckRequestType> createHealthCheckRequest(HealthCheckRequestType value) {
        return new JAXBElement<HealthCheckRequestType>(_HealthCheckRequest_QNAME, HealthCheckRequestType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link FaultResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "faultResponse")
    public JAXBElement<FaultResponseType> createFaultResponse(FaultResponseType value) {
        return new JAXBElement<FaultResponseType>(_FaultResponse_QNAME, FaultResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link FaultDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "FaultDetailsResponseType")
    public JAXBElement<FaultDetailsResponseType> createFaultDetailsResponseType(FaultDetailsResponseType value) {
        return new JAXBElement<FaultDetailsResponseType>(_FaultDetailsResponseType_QNAME,
                FaultDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link AssetResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "assetResponse")
    public JAXBElement<AssetResponseType> createAssetResponse(AssetResponseType value) {
        return new JAXBElement<AssetResponseType>(_AssetResponse_QNAME, AssetResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link LastFaultStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "LastFaultStatusResponseType")
    public JAXBElement<LastFaultStatusResponseType> createLastFaultStatusResponseType(
            LastFaultStatusResponseType value) {
        return new JAXBElement<LastFaultStatusResponseType>(_LastFaultStatusResponseType_QNAME,
                LastFaultStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ToolsParamGroupResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "ToolsParamGroupResponseType")
    public JAXBElement<ToolsParamGroupResponseType> createToolsParamGroupResponseType(
            ToolsParamGroupResponseType value) {
        return new JAXBElement<ToolsParamGroupResponseType>(_ToolsParamGroupResponseType_QNAME,
                ToolsParamGroupResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link RequestHistoryResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "requestHistoryResponse")
    public JAXBElement<RequestHistoryResponseType> createRequestHistoryResponse(RequestHistoryResponseType value) {
        return new JAXBElement<RequestHistoryResponseType>(_RequestHistoryResponse_QNAME,
                RequestHistoryResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link VehicleCommStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "vehicleCommStatusResponse")
    public JAXBElement<VehicleCommStatusResponseType> createVehicleCommStatusResponse(
            VehicleCommStatusResponseType value) {
        return new JAXBElement<VehicleCommStatusResponseType>(_VehicleCommStatusResponse_QNAME,
                VehicleCommStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link FaultLogServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "faultLogServiceResponseType")
    public JAXBElement<FaultLogServiceResponseType> createFaultLogServiceResponseType(
            FaultLogServiceResponseType value) {
        return new JAXBElement<FaultLogServiceResponseType>(_FaultLogServiceResponseType_QNAME,
                FaultLogServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link FaultDataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/assetservice", name = "faultDataResponseType")
    public JAXBElement<FaultDataResponseType> createFaultDataResponseType(FaultDataResponseType value) {
        return new JAXBElement<FaultDataResponseType>(_FaultDataResponseType_QNAME, FaultDataResponseType.class, null,
                value);
    }

}
