//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:15:24 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for parameterResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="parameterResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameterNameID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterResponseType", propOrder = { "parameterNameID", "parameterName", "columnType", "value",
        "paramDBName",
    "displayName",
    "uomAbbr","virtualId" })
@XmlRootElement
public class ParameterResponseType {

    @XmlElement(required = true, name = "id")
    protected String parameterNameID;
    @XmlElement(required = true, name = "name")
    protected String parameterName;
    @XmlElement(required = true, name = "type")
    protected String columnType;
    @XmlElement(required = true, name = "value")
    protected String value;
    @XmlElement(required = true, name = "paramDBName")
    protected String paramDBName;
    @XmlElement(required = true,name="displayName")
    protected String displayName;
    protected String uomAbbr;
    protected String virtualId;

	public String getVirtualId() {
		return virtualId;
	}
	public void setVirtualId(String virtualId) {
		this.virtualId = virtualId;
	}
	public String getUomAbbr() {
		return uomAbbr;
	}

	public void setUomAbbr(String uomAbbr) {
		this.uomAbbr = uomAbbr;
	}
    /**
     * Gets the value of the parameterNameID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParameterNameID() {
        return parameterNameID;
    }

    /**
     * Sets the value of the parameterNameID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setParameterNameID(String value) {
        this.parameterNameID = value;
    }

    /**
     * Gets the value of the parameterName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the columnType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * Sets the value of the columnType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnType(String value) {
        this.columnType = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the paramDBName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParamDBName() {
        return paramDBName;
    }

    /**
     * Sets the value of the paramDBName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setParamDBName(String value) {
        this.paramDBName = value;
    }

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
 
}
