//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 07:24:15 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for roadInitialType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="roadInitialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subDivisionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subDivisionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>   
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subDivisionResponseType", propOrder = { "subDivisionId", "subDivisionName", "regionId", "customerId" })
@XmlRootElement
public class SubDivisionResponseType {
    @XmlElement(required = true)
    protected String subDivisionId;
    @XmlElement(required = true)
    protected String subDivisionName;
    @XmlElement(required = true)
    protected String regionId;
    @XmlElement(required = true)
    protected String customerId;

    /**
     * @return the subDivisionId
     */
    public String getSubDivisionId() {
        return subDivisionId;
    }

    /**
     * @param subDivisionId
     *            the subDivisionId to set
     */
    public void setSubDivisionId(String subDivisionId) {
        this.subDivisionId = subDivisionId;
    }

    /**
     * @return the subDivisionName
     */
    public String getSubDivisionName() {
        return subDivisionName;
    }

    /**
     * @param subDivisionName
     *            the subDivisionName to set
     */
    public void setSubDivisionName(String subDivisionName) {
        this.subDivisionName = subDivisionName;
    }

    /**
     * @return the regionId
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * @param regionId
     *            the regionId to set
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * @return the customerId
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * @param customerId
     *            the customerId to set
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

}
