//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.14 at 08:50:38 PM IST 
//

package com.ge.trans.rmd.services.assets.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ToolParamInfoResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ToolParamInfoResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="headerHtml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dummyHeaderHtml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="upperBound" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lowerBound" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headerWidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixedHeaderWidthTotal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="variableHeaderWidthTotal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataTooltipFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="style" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arlHeader", namespace = "http://omd/omdservices/assetservice", propOrder = { "headerHtml",
        "dummyHeaderHtml", "columnName", "info", "format", "upperBound", "lowerBound", "headerWidth",
        "fixedHeaderWidthTotal", "variableHeaderWidthTotal", "dataTooltipFlag", "style", "filter", "charLength",
        "toolTip" })
public class ToolParamInfoResponseType {

    @XmlElement(required = true)
    protected String headerHtml;
    @XmlElement(required = true)
    protected String dummyHeaderHtml;
    @XmlElement(required = true)
    protected String columnName;
    @XmlElement(required = true)
    protected String info;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(required = true)
    protected String upperBound;
    @XmlElement(required = true)
    protected String lowerBound;
    @XmlElement(required = true)
    protected String headerWidth;
    @XmlElement(required = true)
    protected String fixedHeaderWidthTotal;
    @XmlElement(required = true)
    protected String variableHeaderWidthTotal;
    @XmlElement(required = true)
    protected String dataTooltipFlag;
    @XmlElement(required = true)
    protected String style;
    protected String filter;
    protected String charLength;
    protected String toolTip;

    public String getToolTip() {
        return toolTip;
    }

    public void setToolTip(String toolTip) {
        this.toolTip = toolTip;
    }

    public String getCharLength() {
        return charLength;
    }

    public void setCharLength(String charLength) {
        this.charLength = charLength;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    /**
     * Gets the value of the headerHtml property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHeaderHtml() {
        return headerHtml;
    }

    /**
     * Sets the value of the headerHtml property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setHeaderHtml(final String value) {
        this.headerHtml = value;
    }

    /**
     * Gets the value of the dummyHeaderHtml property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDummyHeaderHtml() {
        return dummyHeaderHtml;
    }

    /**
     * Sets the value of the dummyHeaderHtml property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDummyHeaderHtml(final String value) {
        this.dummyHeaderHtml = value;
    }

    /**
     * Gets the value of the columnName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setColumnName(final String value) {
        this.columnName = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInfo(final String value) {
        this.info = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFormat(final String value) {
        this.format = value;
    }

    /**
     * Gets the value of the upperBound property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpperBound() {
        return upperBound;
    }

    /**
     * Sets the value of the upperBound property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUpperBound(final String value) {
        this.upperBound = value;
    }

    /**
     * Gets the value of the lowerBound property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLowerBound() {
        return lowerBound;
    }

    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLowerBound(final String value) {
        this.lowerBound = value;
    }

    /**
     * Gets the value of the headerWidth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHeaderWidth() {
        return headerWidth;
    }

    /**
     * Sets the value of the headerWidth property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setHeaderWidth(final String value) {
        this.headerWidth = value;
    }

    /**
     * Gets the value of the fixedHeaderWidthTotal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFixedHeaderWidthTotal() {
        return fixedHeaderWidthTotal;
    }

    /**
     * Sets the value of the fixedHeaderWidthTotal property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFixedHeaderWidthTotal(final String value) {
        this.fixedHeaderWidthTotal = value;
    }

    /**
     * Gets the value of the variableHeaderWidthTotal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVariableHeaderWidthTotal() {
        return variableHeaderWidthTotal;
    }

    /**
     * Sets the value of the variableHeaderWidthTotal property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVariableHeaderWidthTotal(final String value) {
        this.variableHeaderWidthTotal = value;
    }

    /**
     * Gets the value of the dataTooltipFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataTooltipFlag() {
        return dataTooltipFlag;
    }

    /**
     * Sets the value of the dataTooltipFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDataTooltipFlag(final String value) {
        this.dataTooltipFlag = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStyle(final String value) {
        this.style = value;
    }

}
