/**
 * ============================================================
 * Classification: GE Confidential
 * File :VehCfgTemplateRequestType.java
 * Description :This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
 				See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 				Any modifications to this file will be lost upon recompilation of the source schema. 
 				Generated on: 2015.03.15 at 01:22:14 PM IST 
 * Package : com.ge.trans.rmd.services.assets.valueobjects
 * Author  : iGATE Global Solutions Ltd.
 * Last Edited By :
 * Version : 1.0
 * Created on :
 * History
 * Modified By : Initial Release
 *
 * Copyright (C) 2009 General Electric Company. All rights reserved
 *
 * ============================================================
 */
package com.ge.trans.rmd.services.assets.valueobjects;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/*******************************************************************************
 * 
 * @Author :
 * @Version : 1.0
 * @Date Created :
 * @Date Modified:
 * @Modified By :
 * @Contact :
 * @Description :
 * @History :
 * 
 ******************************************************************************/

/**
 * <p>
 * Java class for vehCfgTemplateRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="vehCfgTemplateRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *     	   &lt;element name="configFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="title " type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="rnh" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="roadNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 **/

@XmlAccessorType(XmlAccessType.FIELD)

@XmlType(name = "vehCfgTemplateRequestType", propOrder = {
		"objId",
		"configFile",
		"template",
		"version",
		"title",
		"status",
		"assetGrpName",
		"assetNumber",
		"customer",
		"userName",
		"cntrlCnfg",
		"arrVehCfgTemplateRequestType",
		"customerId",
		"vehStatusObjId"
})
@XmlRootElement
public class VehCfgTemplateRequestType {

	@XmlElement(required = true)
	private String objId;
	@XmlElement(required = true)
	private String configFile;
	@XmlElement(required = true)
	private String template;
	@XmlElement(required = true)
	private String version;
	@XmlElement(required = true)
	private String title;
	@XmlElement(required = true)
	private String status;
	@XmlElement(required = true)
	private String assetGrpName;
	@XmlElement(required = true)
	private String assetNumber;
	@XmlElement(required = true)
	private String customer;
	
	@XmlElement(required = true)
	private String userName;
	@XmlElement(required = true)
	private String cntrlCnfg;
	@XmlElement(required = true)
	private List<VehCfgTemplateRequestType> arrVehCfgTemplateRequestType;	
	@XmlElement(required = true)
	private String customerId;
	@XmlElement(required = true)
    private String vehStatusObjId;
	
	public String getCntrlCnfg() {
		return cntrlCnfg;
	}
	public List<VehCfgTemplateRequestType> getArrVehCfgTemplateRequestType() {
		return arrVehCfgTemplateRequestType;
	}
	public void setArrVehCfgTemplateRequestType(
			List<VehCfgTemplateRequestType> arrVehCfgTemplateRequestType) {
		this.arrVehCfgTemplateRequestType = arrVehCfgTemplateRequestType;
	}
	public void setCntrlCnfg(String cntrlCnfg) {
		this.cntrlCnfg = cntrlCnfg;
	}
	
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getObjId() {
		return objId;
	}
	public void setObjId(String objId) {
		this.objId = objId;
	}
	public String getConfigFile() {
		return configFile;
	}
	public void setConfigFile(String configFile) {
		this.configFile = configFile;
	}
	public String getTemplate() {
		return template;
	}
	public void setTemplate(String template) {
		this.template = template;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getAssetGrpName() {
		return assetGrpName;
	}
	public void setAssetGrpName(String assetGrpName) {
		this.assetGrpName = assetGrpName;
	}
	public String getAssetNumber() {
		return assetNumber;
	}
	public void setAssetNumber(String assetNumber) {
		this.assetNumber = assetNumber;
	}
	public String getCustomer() {
		return customer;
	}
	public void setCustomer(String customer) {
		this.customer = customer;
	}
	public String getCustomerId() {
		return customerId;
	}
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
    public String getVehStatusObjId() {
        return vehStatusObjId;
    }
    public void setVehStatusObjId(String vehStatusObjId) {
        this.vehStatusObjId = vehStatusObjId;
    }
	
	
	
}
