//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 04:07:08 PM IST 
//

package com.ge.trans.pp.services.geofenceReport.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for geofenceReportListRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="geofenceReportListRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="geofenceRequestTypeList" type="{http://omd/omdservices/geofencereport}geofenceReportRequestType" maxOccurs="unbounded"/>
 *          &lt;element name="geofences" type="{http://omd/omdservices/geofencereport}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geofenceReportListRequestType", propOrder = { "geofenceRequestTypeList", "geofences","roleId" })
@XmlRootElement
public class GeofenceReportListRequestType {

    @XmlElement(required = true)
    protected List<GeofenceReportRequestType> geofenceRequestTypeList;
    @XmlElement(required = true)
    protected List<String> geofences;
    @XmlElement(required = true)
    protected String roleId;

    /**
     * Gets the value of the geofenceRequestTypeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the geofenceRequestTypeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGeofenceRequestTypeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeofenceReportRequestType }
     * 
     * 
     */
    public List<GeofenceReportRequestType> getGeofenceRequestTypeList() {
        if (geofenceRequestTypeList == null) {
            geofenceRequestTypeList = new ArrayList<GeofenceReportRequestType>();
        }
        return this.geofenceRequestTypeList;
    }

    public void setGeofenceRequestTypeList(List<GeofenceReportRequestType> geofenceRequestTypeList) {
        this.geofenceRequestTypeList = geofenceRequestTypeList;
    }

    public List<String> getGeofences() {
        return geofences;
    }

    public void setGeofences(List<String> geofences) {
        this.geofences = geofences;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    
    
}
