//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 06:51:38 PM IST 
//

package com.ge.trans.rmd.services.authorization.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for privilegeDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="privilegeDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="privilegeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="privilegeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "privilegeDetailsType", propOrder = { "privilegeName", "displayName", "privilegeId", "parentId",
        "enabled", "level", "resourceType", "description", "sortOrder" })
@XmlRootElement
public class PrivilegeDetailsType {

    protected String privilegeName;
    protected String displayName;
    protected Long privilegeId;
    protected Long parentId;
    protected Boolean enabled;
    protected String level;
    protected String resourceType;
    protected String description;
    protected String sortOrder;

    /**
     * Gets the value of the privilegeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * Sets the value of the privilegeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPrivilegeName(String value) {
        this.privilegeName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the privilegeId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * Sets the value of the privilegeId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setPrivilegeId(Long value) {
        this.privilegeId = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setParentId(Long value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSortOrder(String value) {
        this.sortOrder = value;
    }

}
