//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.02 at 09:25:07 PM IST 
//

package com.ge.trans.rmd.services.error.valueobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.ge.trans.rmd.cm.services.error.valueobjects package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RuleMeasureErrorReportResponse_QNAME = new QName("http://omd/omdservices/error",
            "ruleMeasureErrorReportResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.ge.trans.rmd.cm.services.error.valueobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorReportResponseType }
     * 
     */
    public ErrorReportResponseType createErrorReportResponseType() {
        return new ErrorReportResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ErrorReportResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/error", name = "ruleMeasureErrorReportResponse")
    public JAXBElement<ErrorReportResponseType> createRuleMeasureErrorReportResponse(ErrorReportResponseType value) {
        return new JAXBElement<ErrorReportResponseType>(_RuleMeasureErrorReportResponse_QNAME,
                ErrorReportResponseType.class, null, value);
    }

}
