
package com.ge.trans.rmd.cm.mcs.assetslistservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-b02- Generated
 * source version: 2.0
 */
@WebServiceClient(name = "AssetsListServiceInterface", targetNamespace = "http://www.getransporatation.com/railsolutions/mcs", wsdlLocation = "file:/C:/Users/gr806265/Documents/userdata/softwares/jboss-5.1.0.GA/bin/AssetsListService.wsdl")
public class AssetsListServiceInterface extends Service {

    private final static URL ASSETSLISTSERVICEINTERFACE_WSDL_LOCATION;
    private final static Logger logger = Logger
            .getLogger(com.ge.trans.rmd.cm.mcs.assetslistservice.AssetsListServiceInterface.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ge.trans.rmd.cm.mcs.assetslistservice.AssetsListServiceInterface.class.getResource(".");
            url = new URL(baseUrl,
                    "file:/C:/Users/gr806265/Documents/userdata/softwares/jboss-5.1.0.GA/bin/AssetsListService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning(
                    "Failed to create URL for the wsdl Location: 'file:/C:/Users/gr806265/Documents/userdata/softwares/jboss-5.1.0.GA/bin/AssetsListService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ASSETSLISTSERVICEINTERFACE_WSDL_LOCATION = url;
    }

    public AssetsListServiceInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssetsListServiceInterface() {
        super(ASSETSLISTSERVICEINTERFACE_WSDL_LOCATION,
                new QName("http://www.getransporatation.com/railsolutions/mcs", "AssetsListServiceInterface"));
    }

    /**
     * @return returns AssetsListService
     */
    @WebEndpoint(name = "AssetsListServicePort")
    public AssetsListService getAssetsListServicePort(String username, String password) {
        AssetsListService assetsListService = super.getPort(
                new QName("http://www.getransporatation.com/railsolutions/mcs", "AssetsListServiceImplPort"),
                AssetsListService.class);
        BindingProvider bp = (BindingProvider) assetsListService;
        bp.getRequestContext().put(BindingProvider.USERNAME_PROPERTY, username);
        bp.getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, password);
        return assetsListService;
    }

}
