//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.21 at 05:30:20 PM IST 
//


package com.ge.trans.rmd.services.turnover.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for turnoverInboundResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="turnoverInboundResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roadNumberHeader" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roadNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gpocComments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "turnoverInboundResponseType", propOrder = {
    "caseId",
    "roadNumberHeader",
    "roadNumber",
    "gpocComments",
    "count"
})
@XmlRootElement
public class TurnoverInboundResponseType {

    @XmlElement(required = true)
    protected String caseId;
    @XmlElement(required = true)
    protected String roadNumberHeader;
    @XmlElement(required = true)
    protected String roadNumber;
    @XmlElement(required = true)
    protected String gpocComments;
    @XmlElement(required = true)
    protected String count;

    /**
     * Gets the value of the caseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

    /**
     * Gets the value of the roadNumberHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadNumberHeader() {
        return roadNumberHeader;
    }

    /**
     * Sets the value of the roadNumberHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadNumberHeader(String value) {
        this.roadNumberHeader = value;
    }

    /**
     * Gets the value of the roadNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadNumber() {
        return roadNumber;
    }

    /**
     * Sets the value of the roadNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadNumber(String value) {
        this.roadNumber = value;
    }

    /**
     * Gets the value of the gpocComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpocComments() {
        return gpocComments;
    }

    /**
     * Sets the value of the gpocComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpocComments(String value) {
        this.gpocComments = value;
    }

    public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

}
