/**
 * ============================================================
 * Classification: GE Confidential
 * File :AddNotifyConfigRequestType.java
 * Description :This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
 				See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 				Any modifications to this file will be lost upon recompilation of the source schema. 
 				Generated on: 2015.03.15 at 01:22:14 PM IST 
 * Package : com.ge.trans.rmd.services.assets.valueobjects
 * Author  : iGATE Global Solutions Ltd.
 * Last Edited By :
 * Version : 1.0
 * Created on :
 * History
 * Modified By : Initial Release
 *
 * Copyright (C) 2009 General Electric Company. All rights reserved
 *
 * ============================================================
 */
package com.ge.trans.pp.services.manageGeofence.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/*******************************************************************************
 * 
 * @Author :
 * @Version : 1.0
 * @Date Created :
 * @Date Modified:
 * @Modified By :
 * @Contact :
 * @Description :
 * @History :
 * 
 ******************************************************************************/

/**
 * <p>
 * Java class for AddNotifyConfigRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="addNotifyConfigRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *     	   &lt;element name="orgObjId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelObjId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notifyFlagName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="notfyFlagValue " type="{http://www.w3.org/2001/XMLSchema}string"/>
 *        &lt;element name="thresholdName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thresholdValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 **/

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addNotifyConfigRequestType", propOrder = { "userName", "customer", "modelObjId", "notifyFlagName",
        "notfyFlagValue", "thresholdName", "thresholdValue", "model"

})

@XmlRootElement
public class AddNotifyConfigRequestType {

    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String customer;
    @XmlElement(required = true)
    protected String modelObjId;
    @XmlElement(required = true)
    protected String notifyFlagName;
    @XmlElement(required = true)
    protected String notfyFlagValue;
    @XmlElement(required = true)
    protected String thresholdName;
    @XmlElement(required = true)
    protected String thresholdValue;
    @XmlElement(required = true)
    protected String model;

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getModelObjId() {
        return modelObjId;
    }

    public void setModelObjId(String modelObjId) {
        this.modelObjId = modelObjId;
    }

    public String getNotifyFlagName() {
        return notifyFlagName;
    }

    public void setNotifyFlagName(String notifyFlagName) {
        this.notifyFlagName = notifyFlagName;
    }

    public String getNotfyFlagValue() {
        return notfyFlagValue;
    }

    public void setNotfyFlagValue(String notfyFlagValue) {
        this.notfyFlagValue = notfyFlagValue;
    }

    public String getThresholdName() {
        return thresholdName;
    }

    public void setThresholdName(String thresholdName) {
        this.thresholdName = thresholdName;
    }

    public String getThresholdValue() {
        return thresholdValue;
    }

    public void setThresholdValue(String thresholdValue) {
        this.thresholdValue = thresholdValue;
    }

}
