//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 04:08:10 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://omd/omdservices/manageGeofence", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ge.trans.pp.services.manageGeofence.valueobjects;
