/**
 * ============================================================
 * Classification: GE Confidential
 * File :ThresholdResponseType.java
 * Description :This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
 				See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 				Any modifications to this file will be lost upon recompilation of the source schema. 
 				Generated on: 2015.03.15 at 01:22:14 PM IST 
 * Package : com.ge.trans.rmd.services.assets.valueobjects
 * Author  : iGATE Global Solutions Ltd.
 * Last Edited By :
 * Version : 1.0
 * Created on :
 * History
 * Modified By : Initial Release
 *
 * Copyright (C) 2009 General Electric Company. All rights reserved
 *
 * ============================================================
 */
package com.ge.trans.pp.services.manageGeofence.valueobjects;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/*******************************************************************************
 * 
 * @Author :
 * @Version : 1.0
 * @Date Created :
 * @Date Modified:
 * @Modified By :
 * @Contact :
 * @Description :
 * @History :
 * 
 ******************************************************************************/

/**
 * <p>
 * Java class for ThresholdResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="thresholdResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thresholdList " type="{http://www.w3.org/2001/XMLSchema}string"/>
 *     	  &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 **/

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "thresholdResponseType", propOrder = { "thresholdList" })

@XmlRootElement
public class ThresholdResponseType {

    @XmlElement(required = true)
    protected List<String> thresholdList;

    public List<String> getThresholdList() {
        return thresholdList;
    }

    public void setThresholdList(List<String> thresholdList) {
        this.thresholdList = thresholdList;
    }

}
