package com.ge.trans.eoa.services.common.constants;

public final class AlertConstants 
{
	public static final String EOA_SERVICE="EOA";
	public static final String CONFIG_ALERT_SERVICE="Config Alerts";
	public static final String CONFIG_ALERT="Config Alert";
	public static final String ATS_SERVICE="ATS";
	public static final String MODELFAMILY = "modelFamily";
	public static final String PP_EMAIL_NOT_MOVING_NOTIFY ="PP_EMAIL_NOT_MOVING_NOTIFY";
    public static final String PP_EMAIL_LOW_FUEL_NOTIFY ="PP_EMAIL_LOW_FUEL_NOTIFY";
    public static final String PP_EMAIL_FUELING_NOTIFY ="PP_EMAIL_FUELING_NOTIFY";
    public static final String PP_EMAIL_DWELL_NOTIFY ="PP_EMAIL_DWELL_NOTIFY";
    public static final String PP_EMAIL_ENG_STATE_NOTIFY ="PP_EMAIL_ENG_STATE_NOTIFY";
    public static final String PP_EMAIL_ENG_ON_ISOLATE_NOTIFY ="PP_EMAIL_ENG_ON_ISOLATE_NOTIFY";
    public static final String PP_EMAIL_PROXIMITY_NOTIFY ="PP_EMAIL_PROXIMITY_NOTIFY";
    public static final String PP_EMAIL_INTERCHANGE_NOTIFY ="PP_EMAIL_INTERCHANGE_NOTIFY";
    public static final String PP_EMAIL_CONSIST_NOTIFY ="PP_EMAIL_CONSIST_NOTIFY";
    public static final String OPERATOR_PWR_BRAKE_NOTIFY_FLAG ="OPERATOR_PWR_BRAKE_NOTIFY_FLAG";
    public static final String EMER_AIR_BRK_APPLY_NOTIFY_FLAG ="EMER_AIR_BRK_APPLY_NOTIFY_FLAG";
    public static final String AESS_SHUTDOWN_NOTIFY_FLAG ="AESS_SHUTDOWN_NOTIFY_FLAG";
    public static final String ALERT_TMOUT_PNLTY_NOTIFY_FLAG ="ALERT_TMOUT_PNLTY_NOTIFY_FLAG";
    public static final String TO_NOT_USED_NOTIFY_FLAG ="TO_NOT_USED_NOTIFY_FLAG";
    public static final String EVENT_TYPE = "eventType";
    public static final String SERVICE = "serviceType";
    public static final String SD_RECOME_VAL = "sdRecomeval";
    public static final String LOOKUP_VAL = "lookupVal";
    public static final String TITLES = "TITLE";
    public static final String RXSUBSCRIBED_ALERT ="rxsubscribedAlert";
    public static final String RX_ALERT_VALUE ="value";
    public static final String CUSTOMER_OBJ_ID = "customerObjId";
    public static final String EMAIL_FLAG = "emailFlag";
    public static final String EMAIL_FORMAT = "emailFormat";
    public static final String NOTIFICATION_TYPE = "notificationType";
    public static final String SUBSCRIPTION_MODEL = "subscriptionModel";
    public static final String REGION_OBJID = "regionObjId";
    public static final String FLEET_OBJID = "fleetObjId";  
    public static final String SUBREGION_OBJID = "subRegionObjId";  
    public static final String ALERT_CONF_SEQ_ID = "alertConfSeqId";
    public static final String REGIONID="regionId";
    public static final String FLEETID="fleetId";
    public static final String ASSETID="assetId";
    public static final String SHOPID="shopId";
    public static final String SUBDIVISIONID="subdivisionId";
    public static final String CUSTOMER_ALERT_OBJ_ID="customerAlertObjId";
    public static final String NOTIFY_ALERT_OBJ_ID="notify_AlertObjId";
    public static final String ACTIVE_FLAG = "Active";
    public static final String INACTIVE_FLAG = "Inactive";
    public static final String STATUS_FLAG = "statusFlag";
	public static final String ALERT_TYPE_CUSTOMER = "ALERT_TYPE_CUSTOMER";
	public static final String ALERT_TYPE_REGION = "ALERT_TYPE_REGION";
	public static final String ALERT_TYPE_SUB_DIVISION = "ALERT_TYPE_SUBDIVISION";
	public static final String ALERT_TYPE_FLEET = "ALERT_TYPE_FLEET";
	public static final String ALERT_TYPE_ASSET = "ALERT_TYPE_ASSET";
	public static final String ALERT_TYPE_SHOP = "ALERT_TYPE_SHOP";
	public static final String ALERT_TYPE_MODEL = "ALERT_TYPE_MODEL";
	public static final String NOMODEL = "NOModel";
	public static final String RULE_TITLE = "Rule Title";
	public static final String STR_ALERT_TITLE = "strAlertTitle";
	public static final String STR_ALERT_NUMBER_OF_DAYS = "strNumberOfDays";
	public static final String STR_ALERT_FROM_DATE = "strFromDate";
	public static final String STR_ALERT_TO_DATE = "strToDate";
	public static final String STR_ALERT_CUSTOMER= "strCustomer";
	public static final String STR_ALERT_REGION = "strRegion";
	public static final String STR_ALERT_SUB_DIVISION = "strSubDivision";
	public static final String STR_ALERT_MODEL = "strModel";
	public static final String STR_ALERT_FLEET = "strFleet";
	public static final String STR_ALERT_ASSET = "strAsset";
	public static final String STR_ALERT_SHOP = "strShop";
	public static final String STR_ALERT_TYPE = "strType";
	public static final String STR_ALERT_MULTIUSERS = "strMultiUsers";
	public static final String ALERT_CONF_SEQID = " :alertConfSeqId) ";
	public static final String GET_USR_NOTIFY_ALERT_CONF_SEQ = " GET_USR.GET_USR_NOTIFY_ALERT_CONF_SEQ.currval) ";
	public static final String INSERT_GET_USR_NOTIFY_ALERT_CONF = "insert into GET_USR.GET_USR_NOTIFY_ALERT_CONF(OBJID, SERVICE, NOTIFY_EVENT_TYPE, NOTIFY_ALERT_CONF2USERS_SEQID, CREATED_DATE, CREATED_BY, LAST_UPDATED_DATE, LAST_UPDATED_BY,NOTIFY_ALERT_CONF2RX_ALERT,NTFY_ALRT_CNF2RULEHIS_ORGNL_ID) values ";
	public static final String QUERY_CUST_OBJID = " AND CUST.OBJID = :customerObjId ";
	public static final String QUERY_ALERT_TYPE_CUSTOMER = "SELECT ALERTCONF.OBJID, CUSTALERT.ACTIVE_FLAG ";
	public static final String QUERY_RXALERT_VALUE2SD_RECOM = " AND RXALERT.VALUE2SD_RECOM =:value ";
	public static final String QUERY_RXALERT_VALUE2RMD_LOOKUP = " AND RXALERT.VALUE2RMD_LOOKUP =:value ";
	public static final String QUERY_CUSTALERT_CUST_ID2BUS_ORG = " AND CUSTALERT.CUST_ID2BUS_ORG = CUST.OBJID ";
	public static final String QUERY_ALERTCONF_NOTIFY_ALERT_CONF2USERS_SEQID = " AND ALERTCONF.NOTIFY_ALERT_CONF2USERS_SEQID =:userSeqId ";
	public static final String QUERY_ALERTCONF_SERVICE = " AND ALERTCONF.SERVICE = :serviceType ";
	public static final String QUERY_GET_USR_GET_USR_VEHICLE_ALERT = " :emailFormat,:emailFlag,:notificationType,:subscriptionModel, SYSDATE, :userId, SYSDATE, :userId,";
	public static final String QUERY_GET_USR_GET_USR_VEHICLE_ALERT_FOR_FLEET = " :emailFormat,:emailFlag,:subscriptionModel, SYSDATE, :userId, SYSDATE, :userId,";
	public static final String QUERY_CUSTALERT_CONF_ID2NOTIFY_ALERT_CONF = " AND CUSTALERT.CONF_ID2NOTIFY_ALERT_CONF = ALERTCONF.OBJID ";
	public static final String QUERY_CUSTALERT_EMAIL_ATTACHMENT_FORMAT_CD = " AND CUSTALERT.EMAIL_ATTACHMENT_FORMAT_CD = :emailFormat ";
	public static final String QUERY_NOTIFY_EVENT_TYPE = " SA.TABLE_BUS_ORG CUST WHERE UPPER(NOTIFY_EVENT_TYPE) = :eventType ";
	public static final String QUERY_INSERT_GET_USR_NOTIFY_ALERT_CONF = " (GET_USR.GET_USR_NOTIFY_ALERT_CONF_SEQ.nextval,:serviceType,";
	public static final String QUERY_INSERT_GET_USR_NOTIFY_ALERT_CONF_EOA = " (:objId,:serviceType,";
	public static final String SELECT="Select";
	public static final String ALERT_RX="Rx";
	public static final String ALERT_CONFIG="Configurable";
	public static final String ALERT_HST_INTERNAL="(SELECT USER_ID FROM GET_USR.GET_USR_USERS WHERE USER_TYPE IS NOT NULL AND NOT USER_TYPE='Ex Employee' AND STATUS ='1' AND EMAIL_ID IS NOT NULL) ";
	public static final String ALERT_HST_EXTERNAL="(SELECT USER_ID FROM GET_USR.GET_USR_USERS WHERE USER_TYPE='Customer' AND STATUS='1' AND EMAIL_ID IS NOT NULL) ";
	public static final String USER_ID="userId";
	public static final String USER_PHONE_NO="userPhoneNo";
	public static final String USER_PHONE_COUNTRY_CODE="userPhoneCountryCode";
	public static final String RX_TYPE_VALUE ="rxTypeSubscribed";
	public static final String OBJID =":objId)";
	public static final String OBJ_ID ="objId";
	private AlertConstants() {
    }
}
