//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 07:24:52 PM IST 
//

package com.ge.trans.pp.services.idlereport.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for idleReportDetailType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idleReportDetailType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://omd/omdservices/ppidlereport}idleReportRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://omd/omdservices/ppidlereport}idleType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idleReportDetailType", propOrder = { "idleType" })
@XmlRootElement
public class IdleReportDetailType extends IdleReportRequestType {

    @XmlElement(required = true)
    protected String idleType;

    /**
     * Gets the value of the idleType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdleType() {
        return idleType;
    }

    /**
     * Sets the value of the idleType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdleType(String value) {
        this.idleType = value;
    }

}
