//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 07:24:52 PM IST 
//

package com.ge.trans.pp.services.idlereport.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for idleReportDetailResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idleReportDetailResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idleReportDetailResponseRow" type="{http://omd/omdservices/ppidlereport}idleReportDetailResponseRowType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idleReportDetailResponseType", propOrder = { "idleReportDetailResponseRow" })
@XmlRootElement
public class IdleReportDetailResponseType {

    public void setIdleReportDetailResponseRow(List<IdleReportDetailResponseRowType> idleReportDetailResponseRow) {
        this.idleReportDetailResponseRow = idleReportDetailResponseRow;
    }

    protected List<IdleReportDetailResponseRowType> idleReportDetailResponseRow;

    /**
     * Gets the value of the idleReportDetailResponseRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the idleReportDetailResponseRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIdleReportDetailResponseRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdleReportDetailResponseRowType }
     * 
     * 
     */
    public List<IdleReportDetailResponseRowType> getIdleReportDetailResponseRow() {
        if (idleReportDetailResponseRow == null) {
            idleReportDetailResponseRow = new ArrayList<IdleReportDetailResponseRowType>();
        }
        return this.idleReportDetailResponseRow;
    }

}
