//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 07:24:52 PM IST 
//

package com.ge.trans.pp.services.idlereport.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for idleReportSummaryResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idleReportSummaryResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idleReportSummaryResponseRow" type="{http://omd/omdservices/ppidlereport}idleReportSummaryResponseRowType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idleReportSummaryResponseType", propOrder = { "idleReportSummaryResponseRow" })
@XmlRootElement
public class IdleReportSummaryResponseType {

    protected List<IdleReportSummaryResponseRowType> idleReportSummaryResponseRow;

    /**
     * Gets the value of the idleReportSummaryResponseRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the idleReportSummaryResponseRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIdleReportSummaryResponseRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdleReportSummaryResponseRowType }
     * 
     * 
     */
    public List<IdleReportSummaryResponseRowType> getIdleReportSummaryResponseRow() {
        if (idleReportSummaryResponseRow == null) {
            idleReportSummaryResponseRow = new ArrayList<IdleReportSummaryResponseRowType>();
        }
        return this.idleReportSummaryResponseRow;
    }

    public void setIdleReportSummaryResponseRow(List<IdleReportSummaryResponseRowType> idleReportSummaryResponseRow) {
        this.idleReportSummaryResponseRow = idleReportSummaryResponseRow;
    }

}
