//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 09:25:45 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://omd/omdservices/ppidlereport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ge.trans.pp.services.idlereport.valueobjects;
