//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.20 at 08:58:47 PM IST 
//

package com.ge.trans.pp.services.assets.valueobjects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.ge.trans.pp.services.assets.valueobjects package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProdAssetMapRequestType_QNAME = new QName("http://omd/omdservices/ppassets",
            "prodAssetMapRequestType");
    private final static QName _StateInfoType_QNAME = new QName("http://omd/omdservices/ppassets", "stateInfoType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * com.ge.trans.pp.services.assets.valueobjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PpAssetStatusHstryResponseType }
     * 
     */
    public PpAssetStatusHstryResponseType createPpAssetStatusHstryResponseType() {
        return new PpAssetStatusHstryResponseType();
    }

    /**
     * Create an instance of {@link ProdAssetMapRequestType }
     * 
     */
    public ProdAssetMapRequestType createProdAssetMapRequestType() {
        return new ProdAssetMapRequestType();
    }

    /**
     * Create an instance of {@link PpStateResponseType }
     * 
     */
    public PpStateResponseType createPpStateResponseType() {
        return new PpStateResponseType();
    }

    /**
     * Create an instance of {@link PpAssetStatusResponseType }
     * 
     */
    public PpAssetStatusResponseType createPpAssetStatusResponseType() {
        return new PpAssetStatusResponseType();
    }

    /**
     * Create an instance of {@link PpAssetResponseType }
     * 
     */
    public PpAssetResponseType createPpAssetResponseType() {
        return new PpAssetResponseType();
    }

    /**
     * Create an instance of {@link StateInfoType }
     * 
     */
    public StateInfoType createStateInfoType() {
        return new StateInfoType();
    }

    /**
     * Create an instance of {@link PpAssetRequestType }
     * 
     */
    public PpAssetRequestType createPpAssetRequestType() {
        return new PpAssetRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ProdAssetMapRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/ppassets", name = "prodAssetMapRequestType")
    public JAXBElement<ProdAssetMapRequestType> createProdAssetMapRequestType(ProdAssetMapRequestType value) {
        return new JAXBElement<ProdAssetMapRequestType>(_ProdAssetMapRequestType_QNAME, ProdAssetMapRequestType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateInfoType }
     * {@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://omd/omdservices/ppassets", name = "stateInfoType")
    public JAXBElement<StateInfoType> createStateInfoType(StateInfoType value) {
        return new JAXBElement<StateInfoType>(_StateInfoType_QNAME, StateInfoType.class, null, value);
    }

}
