//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.24 at 02:37:49 PM CST 
//

package com.ge.trans.rmd.services.tools.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for scheduleRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="scheduleRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduleRunDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="diagnosticService" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lookbackRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehicleObjid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isCurrentDateRun" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toolRunRequestType", propOrder = { "scheduleRunDate", "diagnosticService", "lookbackRange", "vehicleObjid",
        "isCurrentDateRun","customerId","assetNumber","assetHeader","includeShopData" })
@XmlRootElement
public class ToolRunRequestType {

    @XmlElement(required = true)
    protected String scheduleRunDate;
    @XmlElement(required = true)
    protected String diagnosticService;
    @XmlElement(required = true)
    protected String lookbackRange;
    @XmlElement(required = true)
    protected String vehicleObjid;
    @XmlElement(required = true)    
    protected Boolean isCurrentDateRun;
    @XmlElement(required = true)    
    protected String customerId;
    @XmlElement(required = true)    
    protected String assetNumber;
    @XmlElement(required = true)    
    protected String assetHeader;
    @XmlElement(required = true)    
    protected Boolean includeShopData; 
    
	public Boolean getIncludeShopData() {
		return includeShopData;
	}
	public void setIncludeShopData(Boolean includeShopData) {
		this.includeShopData = includeShopData;
	}
	public String getCustomerId() {
		return customerId;
	}
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
	public String getAssetNumber() {
		return assetNumber;
	}
	public void setAssetNumber(String assetNumber) {
		this.assetNumber = assetNumber;
	}
	public String getAssetHeader() {
		return assetHeader;
	}
	public void setAssetHeader(String assetHeader) {
		this.assetHeader = assetHeader;
	}
	public String getScheduleRunDate() {
		return scheduleRunDate;
	}
	public void setScheduleRunDate(String scheduleRunDate) {
		this.scheduleRunDate = scheduleRunDate;
	}
	public String getDiagnosticService() {
		return diagnosticService;
	}
	public void setDiagnosticService(String diagnosticService) {
		this.diagnosticService = diagnosticService;
	}
	public String getLookbackRange() {
		return lookbackRange;
	}
	public void setLookbackRange(String lookbackRange) {
		this.lookbackRange = lookbackRange;
	}
	public Boolean getIsCurrentDateRun() {
		return isCurrentDateRun;
	}
	public void setIsCurrentDateRun(Boolean isCurrentDateRun) {
		this.isCurrentDateRun = isCurrentDateRun;
	}
	public String getVehicleObjid() {
		return vehicleObjid;
	}
	public void setVehicleObjid(String vehicleObjid) {
		this.vehicleObjid = vehicleObjid;
	}
    
   

}
