//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.27 at 08:40:20 PM IST 
//

package com.ge.trans.rmd.services.rule.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ruleTesterRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ruleTesterRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ruleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noofdays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetNumbers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="userLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleTesterRequestType", propOrder = { "ruleID", "noofdays", "assetNumbers", "userLanguage", "language",
        "userName" })
@XmlRootElement
public class RuleTesterRequestType {

    @XmlElement(required = true)
    protected String ruleID;
    @XmlElement(required = true)
    protected String noofdays;
    @XmlElement(required = true)
    protected List<String> assetNumbers;
    @XmlElement(required = true)
    protected String userLanguage;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String userName;

    /**
     * Gets the value of the ruleID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleID() {
        return ruleID;
    }

    /**
     * Sets the value of the ruleID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleID(String value) {
        this.ruleID = value;
    }

    /**
     * Gets the value of the noofdays property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNoofdays() {
        return noofdays;
    }

    /**
     * Sets the value of the noofdays property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNoofdays(String value) {
        this.noofdays = value;
    }

    /**
     * Gets the value of the assetNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the assetNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAssetNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getAssetNumbers() {
        if (assetNumbers == null) {
            assetNumbers = new ArrayList<String>();
        }
        return this.assetNumbers;
    }

    /**
     * Gets the value of the userLanguage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserLanguage() {
        return userLanguage;
    }

    /**
     * Sets the value of the userLanguage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserLanguage(String value) {
        this.userLanguage = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

}
