//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.25 at 05:12:30 PM IST 
//

package com.ge.trans.rmd.services.rule.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ruleDefinitionConfig complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ruleDefinitionConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configurationID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configurationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleDefinitionConfig", propOrder = { "configuration", "function", "value1", "value2",
        "configurationID", "configurationName" })
@XmlRootElement
public class RuleDefinitionConfig {

    @XmlElement(required = true)
    protected String configuration;
    @XmlElement(required = true)
    protected String function;
    @XmlElement(required = true)
    protected String value1;
    @XmlElement(required = true)
    protected String value2;
    @XmlElement(required = true, name = "id")
    protected String configurationID;
    @XmlElement(required = true, name = "name")
    protected String configurationName;

    /**
     * Gets the value of the configuration property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConfiguration(String value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the value1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue1() {
        return value1;
    }

    /**
     * Sets the value of the value1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue1(String value) {
        this.value1 = value;
    }

    /**
     * Gets the value of the value2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue2() {
        return value2;
    }

    /**
     * Sets the value of the value2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue2(String value) {
        this.value2 = value;
    }

    /**
     * Gets the value of the configurationID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConfigurationID() {
        return configurationID;
    }

    /**
     * Sets the value of the configurationID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConfigurationID(String value) {
        this.configurationID = value;
    }

    /**
     * Gets the value of the configurationName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConfigurationName() {
        return configurationName;
    }

    /**
     * Sets the value of the configurationName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConfigurationName(String value) {
        this.configurationName = value;
    }

}
