//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.16 at 04:10:25 PM IST 
//

package com.ge.trans.rmd.services.rule.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ruleTrackingResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ruleTrackingResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trackingSeqId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="faultRuleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creadtionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastUpdatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bTrackingLink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bTrackingText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleTrackingResponseType", propOrder = { "trackingSeqId", "faultRuleId", "ruleTitle", "ruleType",
        "createdBy", "creadtionDate", "lastUpdatedDate", "status", "bTrackingLink", "bTrackingText" })
@XmlRootElement
public class RuleTrackingResponseType {

    @XmlElement(required = true)
    protected String trackingSeqId;
    @XmlElement(required = true)
    protected String faultRuleId;
    @XmlElement(required = true)
    protected String ruleTitle;
    @XmlElement(required = true)
    protected String ruleType;
    @XmlElement(required = true)
    protected String createdBy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creadtionDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedDate;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String bTrackingLink;
    @XmlElement(required = true)
    protected String bTrackingText;

    /**
     * Gets the value of the trackingSeqId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackingSeqId() {
        return trackingSeqId;
    }

    /**
     * Sets the value of the trackingSeqId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackingSeqId(String value) {
        this.trackingSeqId = value;
    }

    /**
     * Gets the value of the faultRuleId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFaultRuleId() {
        return faultRuleId;
    }

    /**
     * Sets the value of the faultRuleId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFaultRuleId(String value) {
        this.faultRuleId = value;
    }

    /**
     * Gets the value of the ruleTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleTitle() {
        return ruleTitle;
    }

    /**
     * Sets the value of the ruleTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleTitle(String value) {
        this.ruleTitle = value;
    }

    /**
     * Gets the value of the ruleType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * Sets the value of the ruleType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleType(String value) {
        this.ruleType = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the creadtionDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getCreadtionDate() {
        return creadtionDate;
    }

    /**
     * Sets the value of the creadtionDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setCreadtionDate(XMLGregorianCalendar value) {
        this.creadtionDate = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the bTrackingLink property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBTrackingLink() {
        return bTrackingLink;
    }

    /**
     * Sets the value of the bTrackingLink property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBTrackingLink(String value) {
        this.bTrackingLink = value;
    }

    /**
     * Gets the value of the bTrackingText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBTrackingText() {
        return bTrackingText;
    }

    /**
     * Sets the value of the bTrackingText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBTrackingText(String value) {
        this.bTrackingText = value;
    }

}
