//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.16 at 04:10:25 PM IST 
//

package com.ge.trans.rmd.services.rule.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for runRecreatorResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="runRecreatorResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trackingID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createdby" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="finishTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "runRecreatorResponseType", propOrder = { "trackingID", "ruleID", "caseID", "ruleTitle", "createdby",
        "creationTime", "finishTime", "status" })
@XmlRootElement
public class RunRecreatorResponseType {

    @XmlElement(required = true)
    protected String trackingID;
    @XmlElement(required = true)
    protected String ruleID;
    @XmlElement(required = true)
    protected String caseID;
    @XmlElement(required = true)
    protected String ruleTitle;
    @XmlElement(required = true)
    protected String createdby;
    @XmlElement(required = true)
    protected String creationTime;
    @XmlElement(required = true)
    protected String finishTime;
    @XmlElement(required = true)
    protected String status;

    /**
     * Gets the value of the trackingID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTrackingID() {
        return trackingID;
    }

    /**
     * Sets the value of the trackingID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTrackingID(String value) {
        this.trackingID = value;
    }

    /**
     * Gets the value of the ruleID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleID() {
        return ruleID;
    }

    /**
     * Sets the value of the ruleID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleID(String value) {
        this.ruleID = value;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseID(String value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the ruleTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleTitle() {
        return ruleTitle;
    }

    /**
     * Sets the value of the ruleTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleTitle(String value) {
        this.ruleTitle = value;
    }

    /**
     * Gets the value of the createdby property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * Sets the value of the createdby property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedby(String value) {
        this.createdby = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the finishTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * Sets the value of the finishTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFinishTime(String value) {
        this.finishTime = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
