//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 10:12:43 PM IST 
//

package com.ge.trans.rmd.services.rule.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for virtualFilter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="virtualFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filterSeqId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="function" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "virtualFilter", propOrder = { "filterSeqId", "parameter", "function", "value1", "value2" })
@XmlRootElement
public class VirtualFilter {

    @XmlElement(required = true)
    protected String filterSeqId;
    @XmlElement(required = true)
    protected String parameter;
    @XmlElement(required = true)
    protected String function;
    @XmlElement(required = true)
    protected String value1;
    @XmlElement(required = true)
    protected String value2;

    /**
     * Gets the value of the filterSeqId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFilterSeqId() {
        return filterSeqId;
    }

    /**
     * Sets the value of the filterSeqId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFilterSeqId(String value) {
        this.filterSeqId = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setParameter(String value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the value1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue1() {
        return value1;
    }

    /**
     * Sets the value of the value1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue1(String value) {
        this.value1 = value;
    }

    /**
     * Gets the value of the value2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue2() {
        return value2;
    }

    /**
     * Sets the value of the value2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValue2(String value) {
        this.value2 = value;
    }

}
