//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.27 at 05:33:02 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for caseHistoryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="caseHistoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activityDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="who" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activityDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solutionTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayActivity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseSeqId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="descriptionURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseHistoryType", propOrder = { "activity", "activityDate", "who", "activityDesc", "solutionFileName",
        "solutionFilePath", "solutionTitle", "displayActivity", "caseSeqId", "descriptionURL" })
@XmlRootElement
public class CaseHistoryType {

    @XmlElement(required = true)
    protected String activity;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activityDate;
    @XmlElement(required = true)
    protected String who;
    @XmlElement(required = true)
    protected String activityDesc;
    @XmlElement(required = true)
    protected String solutionFileName;
    @XmlElement(required = true)
    protected String solutionFilePath;
    @XmlElement(required = true)
    protected String solutionTitle;
    @XmlElement(required = true)
    protected String displayActivity;
    protected Long caseSeqId;
    protected String descriptionURL;

    public String getDescriptionURL() {
        return descriptionURL;
    }

    public void setDescriptionURL(String descriptionURL) {
        this.descriptionURL = descriptionURL;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setActivity(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the activityDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getActivityDate() {
        return activityDate;
    }

    /**
     * Sets the value of the activityDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setActivityDate(XMLGregorianCalendar value) {
        this.activityDate = value;
    }

    /**
     * Gets the value of the who property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWho() {
        return who;
    }

    /**
     * Sets the value of the who property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWho(String value) {
        this.who = value;
    }

    /**
     * Gets the value of the activityDesc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getActivityDesc() {
        return activityDesc;
    }

    /**
     * Sets the value of the activityDesc property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setActivityDesc(String value) {
        this.activityDesc = value;
    }

    /**
     * Gets the value of the solutionFileName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionFileName() {
        return solutionFileName;
    }

    /**
     * Sets the value of the solutionFileName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionFileName(String value) {
        this.solutionFileName = value;
    }

    /**
     * Gets the value of the solutionFilePath property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionFilePath() {
        return solutionFilePath;
    }

    /**
     * Sets the value of the solutionFilePath property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionFilePath(String value) {
        this.solutionFilePath = value;
    }

    /**
     * Gets the value of the solutionTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionTitle() {
        return solutionTitle;
    }

    /**
     * Sets the value of the solutionTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionTitle(String value) {
        this.solutionTitle = value;
    }

    /**
     * Gets the value of the displayActivity property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisplayActivity() {
        return displayActivity;
    }

    /**
     * Sets the value of the displayActivity property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDisplayActivity(String value) {
        this.displayActivity = value;
    }

    /**
     * Gets the value of the caseSeqId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getCaseSeqId() {
        return caseSeqId;
    }

    /**
     * Sets the value of the caseSeqId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setCaseSeqId(Long value) {
        this.caseSeqId = value;
    }

}
