
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.08 at 03:10:36 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for caseDetailsResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="caseDetailsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseInfo" type="{http://omd/omdservices/caseservice}caseInfoType" maxOccurs="unbounded"/>
 *         &lt;element name="locomotiveInfo" type="{http://omd/omdservices/caseservice}locomotiveInfoType" maxOccurs="unbounded"/>
 *         &lt;element name="caseAttachment" type="{http://omd/omdservices/caseservice}caseAttachmentType" maxOccurs="unbounded"/>
 *         &lt;element name="caseHistory" type="{http://omd/omdservices/caseservice}caseHistoryType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseDetailsResponseType", propOrder = { "caseInfo", "locomotiveInfo", "caseAttachment",
        "caseHistory" })
@XmlRootElement
public class CaseDetailsResponseType {

    @XmlElement(required = true)
    protected List<CaseInfoType> caseInfo;
    @XmlElement(required = true)
    protected List<LocomotiveInfoType> locomotiveInfo;
    @XmlElement(required = true)
    protected List<CaseAttachmentType> caseAttachment;
    @XmlElement(required = true)
    protected List<CaseHistoryType> caseHistory;

    /**
     * Gets the value of the caseInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the caseInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCaseInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseInfoType }
     * 
     * 
     */
    public List<CaseInfoType> getCaseInfo() {
        if (caseInfo == null) {
            caseInfo = new ArrayList<CaseInfoType>();
        }
        return this.caseInfo;
    }

    /**
     * Gets the value of the locomotiveInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the locomotiveInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLocomotiveInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocomotiveInfoType }
     * 
     * 
     */
    public List<LocomotiveInfoType> getLocomotiveInfo() {
        if (locomotiveInfo == null) {
            locomotiveInfo = new ArrayList<LocomotiveInfoType>();
        }
        return this.locomotiveInfo;
    }

    /**
     * Gets the value of the caseAttachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the caseAttachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCaseAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseAttachmentType }
     * 
     * 
     */
    public List<CaseAttachmentType> getCaseAttachment() {
        if (caseAttachment == null) {
            caseAttachment = new ArrayList<CaseAttachmentType>();
        }
        return this.caseAttachment;
    }

    /**
     * Gets the value of the caseHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the caseHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCaseHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseHistoryType }
     * 
     * 
     */
    public List<CaseHistoryType> getCaseHistory() {
        if (caseHistory == null) {
            caseHistory = new ArrayList<CaseHistoryType>();
        }
        return this.caseHistory;
    }

}
