//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:39:24 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CaseTypeResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CaseTypeResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseTypeSeqId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseTypeTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseTypeResponseType", propOrder = { "caseTypeSeqId", "caseTypeTitle" })
@XmlRootElement
public class CaseTypeResponseType {

    protected String caseTypeSeqId;
    protected String caseTypeTitle;

    /**
     * Gets the value of the caseTypeSeqId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseTypeSeqId() {
        return caseTypeSeqId;
    }

    /**
     * Sets the value of the caseTypeSeqId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseTypeSeqId(String value) {
        this.caseTypeSeqId = value;
    }

    /**
     * Gets the value of the caseTypeTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseTypeTitle() {
        return caseTypeTitle;
    }

    /**
     * Sets the value of the caseTypeTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseTypeTitle(String value) {
        this.caseTypeTitle = value;
    }

}
