//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.30 at 06:15:44 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.ge.trans.rmd.services.solutions.valueobjects.SolutionDetailType;

/**
 * <p>
 * Java class for caseRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="caseRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="queueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solutionTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estRepairTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *		   &lt;element name="currentOwnerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StrEstRepairTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseRequestType", propOrder = { "caseID", "caseTitle", "caseType", "queueName", "userName",
        "assetNumber", "customerId", "assetGrpName", "solutionTitle", "urgency", "estRepairTime", "language",
        "userLanguage", "version", "firstName", "lastName", "currentOwnerName", "customerName", "priority", "userId",
        "noOfDays", "queueId", "caseObjid", "assetNumberList", "objSolutionDetailType", "isMassApplyRx",
        "StrEstRepairTime", "msdcNotes", "caseLike", "searchTypeFlag", "appendFlag","lstAttachment" })
@XmlRootElement
public class CaseRequestType {

    @XmlElement(required = true)
    protected String caseID;
    @XmlElement(required = true)
    protected String noOfDays;
    @XmlElement(required = true)
    protected String caseTitle;
    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String caseType;
    @XmlElement(required = true)
    protected String queueName;
    @XmlElement(required = true)
    protected String userName;
    protected String assetNumber;
    protected String customerId;
    protected String assetGrpName;
    protected String solutionTitle;
    protected String urgency;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estRepairTime;
    protected String language;
    protected String userLanguage;
    protected Integer version;
    protected String priority;
    protected String customerName;
    protected String firstName;
    protected String lastName;
    protected String currentOwnerName;
    @XmlElement(required = true)
    protected long queueId;
    @XmlElement(required = true)
    protected String caseObjid;
    @XmlElement(required = true)
    protected List<String> assetNumberList;
    protected String appendFlag;
    protected List<RxDelvDocType> lstAttachment;
        
    public List<RxDelvDocType> getLstAttachment() {
		return lstAttachment;
	}

	public void setLstAttachment(List<RxDelvDocType> lstAttachment) {
		this.lstAttachment = lstAttachment;
	}

	public String getAppendFlag() {
        return appendFlag;
    }

    public void setAppendFlag(String appendFlag) {
        this.appendFlag = appendFlag;
    }

    @XmlElement(required = true)
    protected SolutionDetailType objSolutionDetailType;

    @XmlElement(required = true)
    protected String isMassApplyRx;

    @XmlElement(required = true)
    protected String StrEstRepairTime;

    @XmlElement(required = true)
    protected String msdcNotes;
    protected String caseLike;
    protected String searchTypeFlag;

    public String getCaseLike() {
        return caseLike;
    }

    public void setCaseLike(String caseLike) {
        this.caseLike = caseLike;
    }

    public String getMsdcNotes() {
        return msdcNotes;
    }

    public void setMsdcNotes(String msdcNotes) {
        this.msdcNotes = msdcNotes;
    }

    public String getStrEstRepairTime() {
        return StrEstRepairTime;
    }

    public void setStrEstRepairTime(String strEstRepairTime) {
        StrEstRepairTime = strEstRepairTime;
    }

    public String getSearchTypeFlag() {
        return searchTypeFlag;
    }

    public void setSearchTypeFlag(String searchTypeFlag) {
        this.searchTypeFlag = searchTypeFlag;
    }

    public String getIsMassApplyRx() {
        return isMassApplyRx;
    }

    public void setIsMassApplyRx(String isMassApplyRx) {
        this.isMassApplyRx = isMassApplyRx;
    }

    public SolutionDetailType getObjSolutionDetailType() {
        return objSolutionDetailType;
    }

    public void setObjSolutionDetailType(SolutionDetailType objSolutionDetailType) {
        this.objSolutionDetailType = objSolutionDetailType;
    }

    public List<String> getAssetNumberList() {
        return assetNumberList;
    }

    public void setAssetNumberList(List<String> assetNumberList) {
        this.assetNumberList = assetNumberList;
    }

    public String getCaseObjid() {
        return caseObjid;
    }

    public void setCaseObjid(String caseObjid) {
        this.caseObjid = caseObjid;
    }

    public long getQueueId() {
        return queueId;
    }

    public void setQueueId(long queueId) {
        this.queueId = queueId;
    }

    public String getNoOfDays() {
        return noOfDays;
    }

    public void setNoOfDays(String noOfDays) {
        this.noOfDays = noOfDays;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getAssetGrpName() {
        return assetGrpName;
    }

    public void setAssetGrpName(String assetGrpName) {
        this.assetGrpName = assetGrpName;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseID(String value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the caseTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseTitle() {
        return caseTitle;
    }

    /**
     * Sets the value of the caseTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseTitle(String value) {
        this.caseTitle = value;
    }

    /**
     * Gets the value of the caseType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseType(String value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the queueName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the solutionTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionTitle() {
        return solutionTitle;
    }

    /**
     * Sets the value of the solutionTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionTitle(String value) {
        this.solutionTitle = value;
    }

    /**
     * Gets the value of the urgency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUrgency() {
        return urgency;
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUrgency(String value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the estRepairTime property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getEstRepairTime() {
        return estRepairTime;
    }

    /**
     * Sets the value of the estRepairTime property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setEstRepairTime(XMLGregorianCalendar value) {
        this.estRepairTime = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the userLanguage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserLanguage() {
        return userLanguage;
    }

    /**
     * Sets the value of the userLanguage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserLanguage(String value) {
        this.userLanguage = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setVersion(Integer value) {
        this.version = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the currentOwnerName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrentOwnerName() {
        return currentOwnerName;
    }

    /**
     * Sets the value of the currentOwnerName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrentOwnerName(String value) {
        this.currentOwnerName = value;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
