//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.07 at 02:42:21 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.ge.trans.rmd.services.assets.valueobjects.ProdAssetMapRequestType;
import com.ge.trans.rmd.services.solutions.valueobjects.SolutionDetailType;

/**
 * <p>
 * Java class for casesRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="casesRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="noDays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="queueName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rxCaseID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>         
 *         &lt;element name="caseTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solutionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solutionTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solFeedback" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solutionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ruleDefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetGrName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estRepTm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rxId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fleetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dwq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prodAssetMap" type="{http://omd/omdservices/caseservice}prodAssetMapRequestType" maxOccurs="unbounded"/>
 *         &lt;element name="closedRxLookBackDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="searchTypeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseLike" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMyCases" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *		   &lt;element name="caseObjId" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *         &lt;element name="revisionNo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *         &lt;element name="rxObjId" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *         &lt;element name="assetGrpName" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *         &lt;element name="isLastFault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/> 
 *      &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "casesRequestType", propOrder = { "noDays", "language", "assetHeader", "queueName", "assetNumber",
        "caseID", "rxCaseID", "caseTitle", "caseStatus", "userName", "startDate", "endDate", "solutionStatus",
        "solutionTitle", "solFeedback", "solutionId", "ruleDefId", "customerId", "assetGrName", "estRepTm", "urgency",
        "rxId", "caseType", "modelId", "fleetId", "dwq", "prodAssetMap", "userID", "userLanguage",
        "closedRxLookBackDays", "isMyCases", "searchTypeFlag", "caseLike", "caseObjId", "revisionNo", "rxObjId",
        "solutionDetailType","assetGrpName","isLastFault","screenName"})
@XmlRootElement
public class CasesRequestType {

    protected String noDays;
    protected String language;
    protected String assetHeader;
    protected String queueName;
    protected String assetNumber;
    protected String caseID;
    protected String rxCaseID;
    protected String caseTitle;
    protected String caseStatus;
    protected String userName;
    protected String startDate;
    protected String endDate;
    protected String solutionStatus;
    protected String solutionTitle;
    protected String solFeedback;
    protected String solutionId;
    protected String ruleDefId;
    protected String customerId;
    protected String assetGrName;
    protected String estRepTm;
    protected String urgency;
    protected String rxId;
    protected String caseType;
    protected String modelId;
    protected String fleetId;
    protected String dwq;
    protected String userID;
    protected String userLanguage;
    protected String searchTypeFlag;
    protected String caseLike;
    @XmlElement(required = true)
    protected List<ProdAssetMapRequestType> prodAssetMap;
    @XmlElement(required = true)
    protected List<SolutionDetailType> solutionDetailType;
    protected int closedRxLookBackDays;
    protected Boolean isMyCases;
    protected String caseObjId;
    protected String revisionNo;
    protected Long rxObjId;
    protected String assetGrpName;
    protected boolean isLastFault;
    protected String screenName;
    

    public List<SolutionDetailType> getSolutionDetailType() {
        return solutionDetailType;
    }

    public void setSolutionDetailType(List<SolutionDetailType> solutionDetailType) {
        this.solutionDetailType = solutionDetailType;
    }

    public String getRevisionNo() {
        return revisionNo;
    }

    public void setRevisionNo(String revisionNo) {
        this.revisionNo = revisionNo;
    }

    public Long getRxObjId() {
        return rxObjId;
    }

    public void setRxObjId(Long rxObjId) {
        this.rxObjId = rxObjId;
    }

    public String getCaseObjId() {
        return caseObjId;
    }

    public void setCaseObjId(String caseObjId) {
        this.caseObjId = caseObjId;
    }

    public String getRxCaseID() {
        return rxCaseID;
    }

    public void setRxCaseID(String rxCaseID) {
        this.rxCaseID = rxCaseID;
    }

    /**
     * Gets the value of the noDays property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNoDays() {
        return noDays;
    }

    public String getCaseLike() {
        return caseLike;
    }

    public void setCaseLike(String caseLike) {
        this.caseLike = caseLike;
    }

    public String getSearchTypeFlag() {
        return searchTypeFlag;
    }

    public void setSearchTypeFlag(String searchTypeFlag) {
        this.searchTypeFlag = searchTypeFlag;
    }

    /**
     * Sets the value of the noDays property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNoDays(String value) {
        this.noDays = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the assetHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetHeader() {
        return assetHeader;
    }

    /**
     * Sets the value of the assetHeader property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetHeader(String value) {
        this.assetHeader = value;
    }

    /**
     * Gets the value of the queueName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getQueueName() {
        return queueName;
    }

    /**
     * Sets the value of the queueName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setQueueName(String value) {
        this.queueName = value;
    }

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseID(String value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the caseTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseTitle() {
        return caseTitle;
    }

    /**
     * Sets the value of the caseTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseTitle(String value) {
        this.caseTitle = value;
    }

    /**
     * Gets the value of the caseStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseStatus() {
        return caseStatus;
    }

    /**
     * Sets the value of the caseStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseStatus(String value) {
        this.caseStatus = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the solutionStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionStatus() {
        return solutionStatus;
    }

    /**
     * Sets the value of the solutionStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionStatus(String value) {
        this.solutionStatus = value;
    }

    /**
     * Gets the value of the solutionTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionTitle() {
        return solutionTitle;
    }

    /**
     * Sets the value of the solutionTitle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionTitle(String value) {
        this.solutionTitle = value;
    }

    /**
     * Gets the value of the solFeedback property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolFeedback() {
        return solFeedback;
    }

    /**
     * Sets the value of the solFeedback property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolFeedback(String value) {
        this.solFeedback = value;
    }

    /**
     * Gets the value of the solutionId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSolutionId() {
        return solutionId;
    }

    /**
     * Sets the value of the solutionId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSolutionId(String value) {
        this.solutionId = value;
    }

    /**
     * Gets the value of the ruleDefId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleDefId() {
        return ruleDefId;
    }

    /**
     * Sets the value of the ruleDefId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleDefId(String value) {
        this.ruleDefId = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the assetGrName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetGrName() {
        return assetGrName;
    }

    /**
     * Sets the value of the assetGrName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetGrName(String value) {
        this.assetGrName = value;
    }

    /**
     * Gets the value of the estRepTm property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEstRepTm() {
        return estRepTm;
    }

    /**
     * Sets the value of the estRepTm property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEstRepTm(String value) {
        this.estRepTm = value;
    }

    /**
     * Gets the value of the urgency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUrgency() {
        return urgency;
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUrgency(String value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the rxId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRxId() {
        return rxId;
    }

    /**
     * Sets the value of the rxId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRxId(String value) {
        this.rxId = value;
    }

    /**
     * Gets the value of the caseType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseType(String value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the modelId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * Sets the value of the modelId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModelId(String value) {
        this.modelId = value;
    }

    /**
     * Gets the value of the fleetId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFleetId() {
        return fleetId;
    }

    /**
     * Sets the value of the fleetId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFleetId(String value) {
        this.fleetId = value;
    }

    /**
     * Gets the value of the dwq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDwq() {
        return dwq;
    }

    /**
     * Sets the value of the dwq property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDwq(String value) {
        this.dwq = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the userLanguage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserLanguage() {
        return userLanguage;
    }

    /**
     * Sets the value of the userLanguage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserLanguage(String value) {
        this.userLanguage = value;
    }

    /**
     * Gets the value of the prodAssetMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the prodAssetMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getProdAssetMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProdAssetMapRequestType }
     * 
     * 
     */
    public List<ProdAssetMapRequestType> getProdAssetMap() {
        if (prodAssetMap == null) {
            prodAssetMap = new ArrayList<ProdAssetMapRequestType>();
        }
        return this.prodAssetMap;
    }

    /**
     * Gets the value of the closedRxLookBackDays property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public int getClosedRxlookBackDays() {
        return closedRxLookBackDays;
    }

    /**
     * Sets the value of the closedRxLookBackDays property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setClosedRxlookBackDays(int value) {
        this.closedRxLookBackDays = value;
    }

    /**
     * Gets the value of the isMyCases property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getIsMyCases() {
        return isMyCases;
    }

    /**
     * Sets the value of the isMyCases property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setIsMyCases(Boolean value) {
        this.isMyCases = value;
    }

	public String getAssetGrpName() {
		return assetGrpName;
	}

	public void setAssetGrpName(String assetGrpName) {
		this.assetGrpName = assetGrpName;
	}

	public boolean isLastFault() {
		return isLastFault;
	}

	public void setLastFault(boolean isLastFault) {
		this.isLastFault = isLastFault;
	}

	public void setProdAssetMap(List<ProdAssetMapRequestType> prodAssetMap) {
		this.prodAssetMap = prodAssetMap;
	}

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
	
	

}
