//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 01:55:00 PM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for caseResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="caseResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseInfo" type="{http://omd/omdservices/caseservice}caseInfoType"/>
 *         &lt;element name="solutionInfo" type="{http://omd/omdservices/caseservice}solutionInfoType" maxOccurs="unbounded"/>
 *         &lt;element name="append" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetGrpName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FleetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rowVersion" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rxType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseResponseType", propOrder = { "caseInfo", "solutionInfo", "append", "creator", "assetNumber",
        "assetGrpName", "urgency", "caseId", "modelName", "fleetName", "rowVersion", "customerName", "creationDate",
        "condition", "closeDate", "callType", "caseTitle","rxType" })
@XmlRootElement
public class CaseResponseType {

    @XmlElement(required = true)
    protected CaseInfoType caseInfo;
    @XmlElement(required = true)
    protected List<SolutionInfoType> solutionInfo;
    @XmlElement(required = true)
    protected String append;
    @XmlElement(required = true)
    protected String creator;
    protected String assetNumber;
    protected String assetGrpName;
    protected String urgency;
    protected String caseId;
    protected String modelName;
    @XmlElement(name = "FleetName")
    protected String fleetName;
    protected Integer rowVersion;
    @XmlElement(required = true)
    protected String customerName;
    @XmlElement(required = true)
    protected String creationDate;
    @XmlElement(required = true)
    protected String condition;
    @XmlElement(required = true)
    protected String closeDate;
    @XmlElement(required = true)
    protected String callType;
    @XmlElement(required = true)
    protected String caseTitle;
    @XmlElement(required = true)
    protected String rxType;
    public String getRxType() {
		return rxType;
	}

	public void setRxType(String rxType) {
		this.rxType = rxType;
	}

	public String getCaseTitle() {
        return caseTitle;
    }

    public void setCaseTitle(String caseTitle) {
        this.caseTitle = caseTitle;
    }

    public String getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public String getCloseDate() {
        return closeDate;
    }

    public void setCloseDate(String closeDate) {
        this.closeDate = closeDate;
    }

    public String getCallType() {
        return callType;
    }

    public void setCallType(String callType) {
        this.callType = callType;
    }

    /**
     * Gets the value of the caseInfo property.
     * 
     * @return possible object is {@link CaseInfoType }
     * 
     */
    public CaseInfoType getCaseInfo() {
        return caseInfo;
    }

    /**
     * Sets the value of the caseInfo property.
     * 
     * @param value
     *            allowed object is {@link CaseInfoType }
     * 
     */
    public void setCaseInfo(CaseInfoType value) {
        this.caseInfo = value;
    }

    /**
     * Gets the value of the solutionInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the solutionInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSolutionInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolutionInfoType }
     * 
     * 
     */
    public List<SolutionInfoType> getSolutionInfo() {
        if (solutionInfo == null) {
            solutionInfo = new ArrayList<SolutionInfoType>();
        }
        return this.solutionInfo;
    }

    public void setSolutionInfo(List<SolutionInfoType> solutionInfo) {
        this.solutionInfo = solutionInfo;
    }

    /**
     * Gets the value of the append property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAppend() {
        return append;
    }

    /**
     * Sets the value of the append property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAppend(String value) {
        this.append = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the assetNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * Sets the value of the assetNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetNumber(String value) {
        this.assetNumber = value;
    }

    /**
     * Gets the value of the assetGrpName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetGrpName() {
        return assetGrpName;
    }

    /**
     * Sets the value of the assetGrpName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetGrpName(String value) {
        this.assetGrpName = value;
    }

    /**
     * Gets the value of the urgency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUrgency() {
        return urgency;
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUrgency(String value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the caseId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the fleetName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFleetName() {
        return fleetName;
    }

    /**
     * Sets the value of the fleetName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFleetName(String value) {
        this.fleetName = value;
    }

    /**
     * Gets the value of the rowVersion property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * Sets the value of the rowVersion property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setRowVersion(Integer value) {
        this.rowVersion = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

}
