//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 10:18:28 AM IST 
//

package com.ge.trans.rmd.services.cases.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for rxDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="rxDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rxCaseID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rxScoreCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rxFeedBack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="repaircodeList" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="eoaUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rxDetailsType", propOrder = { "caseID", "rxCaseID", "rxScoreCode", "rxFeedBack", "userName",
        "repaircodeList", "eoaUserName", "rxNote", "fdbkType", "isScoreRx", "rxnotes", "isReissue", "rxTitle",
        "noOfCases", "mdscPerformance" })
@XmlRootElement
public class RxDetailsType {

    @XmlElement(required = true)
    protected String caseID;
    @XmlElement(required = true)
    protected String rxCaseID;
    @XmlElement(required = true)
    protected String rxScoreCode;
    @XmlElement(required = true)
    protected String rxFeedBack;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(type = Long.class)
    protected List<Long> repaircodeList;
    @XmlElement(required = true)
    protected String eoaUserName;
    @XmlElement(required = true)
    protected String rxNote;
    @XmlElement(required = true)
    protected String fdbkType;
    @XmlElement(required = true)
    protected boolean isScoreRx = false;
    @XmlElement(required = true)
    protected String rxnotes;
    @XmlElement(required = true)
    protected String isReissue;
    @XmlElement(required = true)
    protected String rxTitle;
    @XmlElement(required = true)
    protected String noOfCases;
    @XmlElement(required = true)
    protected String mdscPerformance;

    public String getMdscPerformance() {
        return mdscPerformance;
    }

    public void setMdscPerformance(String mdscPerformance) {
        this.mdscPerformance = mdscPerformance;
    }

    public String getRxTitle() {
        return rxTitle;
    }

    public void setRxTitle(String rxTitle) {
        this.rxTitle = rxTitle;
    }

    public String getNoOfCases() {
        return noOfCases;
    }

    public void setNoOfCases(String noOfCases) {
        this.noOfCases = noOfCases;
    }

    public String getRxnotes() {
        return rxnotes;
    }

    public void setRxnotes(String rxnotes) {
        this.rxnotes = rxnotes;
    }

    public String getIsReissue() {
        return isReissue;
    }

    public void setIsReissue(String isReissue) {
        this.isReissue = isReissue;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaseID(String value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the rxCaseID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRxCaseID() {
        return rxCaseID;
    }

    /**
     * Sets the value of the rxCaseID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRxCaseID(String value) {
        this.rxCaseID = value;
    }

    /**
     * Gets the value of the rxScoreCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRxScoreCode() {
        return rxScoreCode;
    }

    /**
     * Sets the value of the rxScoreCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRxScoreCode(String value) {
        this.rxScoreCode = value;
    }

    /**
     * Gets the value of the rxFeedBack property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRxFeedBack() {
        return rxFeedBack;
    }

    /**
     * Sets the value of the rxFeedBack property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRxFeedBack(String value) {
        this.rxFeedBack = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the repaircodeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the repaircodeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRepaircodeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Long }
     * 
     * 
     */
    public List<Long> getRepaircodeList() {
        if (repaircodeList == null) {
            repaircodeList = new ArrayList<Long>();
        }
        return this.repaircodeList;
    }

    /**
     * Gets the value of the eoaUserName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEoaUserName() {
        return eoaUserName;
    }

    /**
     * Sets the value of the eoaUserName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEoaUserName(String value) {
        this.eoaUserName = value;
    }

    public String getRxNote() {
        return rxNote;
    }

    public void setRxNote(String rxNote) {
        this.rxNote = rxNote;
    }

    public String getFdbkType() {
        return fdbkType;
    }

    public void setFdbkType(String fdbkType) {
        this.fdbkType = fdbkType;
    }

    public boolean isScoreRx() {
        return isScoreRx;
    }

    public void setScoreRx(boolean isScoreRx) {
        this.isScoreRx = isScoreRx;
    }

    public void setRepaircodeList(List<Long> repaircodeList) {
        this.repaircodeList = repaircodeList;
    }

}