/**
 * ============================================================
 * Classification: GE Confidential
 * File :QueueDetailsResponseType.java
 * Description :This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
 				See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 				Any modifications to this file will be lost upon recompilation of the source schema. 
 				Generated on: 2015.03.15 at 01:22:14 PM IST 
 * Package : com.ge.trans.rmd.services.cases.valueobjects
 * Author  : iGATE Global Solutions Ltd.
 * Last Edited By :
 * Version : 1.0
 * Created on :
 * History
 * Modified By : Initial Release
 *
 * Copyright (C) 2009 General Electric Company. All rights reserved
 *
 * ============================================================
 */

package com.ge.trans.rmd.services.cases.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/*******************************************************************************
 * 
 * @Author :
 * @Version : 1.0
 * @Date Created :21-July-2015
 * @Date Modified:21-July-2015
 * @Modified By :
 * @Contact :
 * @Description :
 * @History :
 * 
 ******************************************************************************/
/**
 * <p>
 * Java class for ViewLogReponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="viewLogReponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}XMLGregorianCalendar"/>
 *      &lt;element name="roadNumberHeader" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;element name="roadNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *      &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 **/

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "viewLogReponseType", propOrder = { "creationDate", "roadNumberHeader", "roadNumber", "caseId",
        "rxQueue", "customerId", "caseTitle", "caseObjId" })
@XmlRootElement
public class ViewLogReponseType {

    @XmlElement(required = true)
    private XMLGregorianCalendar creationDate;
    @XmlElement(required = true)
    private String roadNumberHeader;
    @XmlElement(required = true)
    private String roadNumber;
    @XmlElement(required = true)
    private String caseId;
    @XmlElement(required = true)
    private String rxQueue;

    @XmlElement(required = true)
    private String customerId;

    private String caseTitle;
    private String caseObjId;

    public String getCaseObjId() {
        return caseObjId;
    }

    public void setCaseObjId(String caseObjId) {
        this.caseObjId = caseObjId;
    }

    public String getCaseTitle() {
        return caseTitle;
    }

    public void setCaseTitle(String caseTitle) {
        this.caseTitle = caseTitle;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(XMLGregorianCalendar creationDate) {
        this.creationDate = creationDate;
    }

    public String getRoadNumberHeader() {
        return roadNumberHeader;
    }

    public void setRoadNumberHeader(String roadNumberHeader) {
        this.roadNumberHeader = roadNumberHeader;
    }

    public String getRoadNumber() {
        return roadNumber;
    }

    public void setRoadNumber(String roadNumber) {
        this.roadNumber = roadNumber;
    }

    public String getCaseId() {
        return caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    public String getRxQueue() {
        return rxQueue;
    }

    public void setRxQueue(String rxQueue) {
        this.rxQueue = rxQueue;
    }

}
