//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.11 at 05:25:56 AM IST 
//

package com.ge.trans.rmd.services.security.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for templateSummaryRequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="templateSummaryRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="templateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="templateDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="view" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fleet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "templateSummaryRequestType", propOrder = { "templateID", "templateName", "templateDesc", "view",
        "service", "customer", "fleet", "model", "level", "status", "createdBy" })
@XmlRootElement
public class TemplateSummaryRequestType {

    protected long templateID;
    @XmlElement(required = true)
    protected String templateName;
    @XmlElement(required = true)
    protected String templateDesc;
    @XmlElement(required = true)
    protected String view;
    @XmlElement(required = true)
    protected String service;
    @XmlElement(required = true)
    protected String customer;
    @XmlElement(required = true)
    protected String fleet;
    @XmlElement(required = true)
    protected String model;
    protected int level;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String createdBy;

    /**
     * Gets the value of the templateID property.
     * 
     */
    public long getTemplateID() {
        return templateID;
    }

    /**
     * Sets the value of the templateID property.
     * 
     */
    public void setTemplateID(long value) {
        this.templateID = value;
    }

    /**
     * Gets the value of the templateName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * Sets the value of the templateName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTemplateName(String value) {
        this.templateName = value;
    }

    /**
     * Gets the value of the templateDesc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTemplateDesc() {
        return templateDesc;
    }

    /**
     * Sets the value of the templateDesc property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTemplateDesc(String value) {
        this.templateDesc = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setView(String value) {
        this.view = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the fleet property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFleet() {
        return fleet;
    }

    /**
     * Sets the value of the fleet property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFleet(String value) {
        this.fleet = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the level property.
     * 
     */
    public int getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     */
    public void setLevel(int value) {
        this.level = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

}
