//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 07:32:23 PM IST 
//

package com.ge.trans.rmd.services.kpi.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for kpi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="kpiRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kpiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noDays" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kpiRequestType", propOrder = { "kpiName", "noDays" })
@XmlRootElement
public class KpiRequestType {

    @XmlElement(required = true)
    protected String kpiName;
    protected long noDays;

    /**
     * Gets the value of the kpiName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getKpiName() {
        return kpiName;
    }

    /**
     * Sets the value of the kpiName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setKpiName(String value) {
        this.kpiName = value;
    }

    /**
     * Gets the value of the noDays property.
     * 
     */
    public long getNoDays() {
        return noDays;
    }

    /**
     * Sets the value of the noDays property.
     * 
     */
    public void setNoDays(long value) {
        this.noDays = value;
    }

}
