//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.17 at 06:18:54 PM IST 
//

package com.ge.trans.rmd.services.kep.knowledgeseeker.valueobjects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for summaryDataResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="summaryDataResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseDataResponseType" type="{http://omd/omdservices/knowledgeSeekerService}baseDataResponseType"/>
 *         &lt;element name="segmentWindow" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classificationWindow" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classificationStepSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="progExclude" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="normalCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supportLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="analysisFailureCases" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="analysisNormalCases" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="filterFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="failureType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataFilter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="daysAfterEvent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="algorithmSelection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverageAnalysis" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="classification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rootCause" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="symptoms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feAssets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="seAssets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="normalSegments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="failureSegments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totAssetsAnalysed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ruleMiningStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleMiningEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "summaryDataResponseType", propOrder = { "baseDataResponseType", "segmentWindow",
        "classificationWindow", "classificationStepSize", "progExclude", "normalCondition", "supportLevel",
        "analysisFailureCases", "analysisNormalCases", "dateRange", "filterFlag", "failureType", "dataFilter",
        "daysAfterEvent", "algorithmSelection", "coverageAnalysis", "classification", "rootCause", "symptoms",
        "feAssets", "seAssets", "normalSegments", "failureSegments", "totAssetsAnalysed", "ruleMiningStartDate",
        "ruleMiningEndDate", "faultCode", "runAgainst", "rxDesc" })
@XmlRootElement
public class SummaryDataResponseType {

    @XmlElement(required = true)
    protected BaseDataResponseType baseDataResponseType;
    @XmlElement(required = true)
    protected int segmentWindow;
    @XmlElement(required = true)
    protected int classificationWindow;
    @XmlElement(required = true)
    protected int classificationStepSize;
    @XmlElement(required = true)
    protected int progExclude;
    @XmlElement(required = true)
    protected String normalCondition;
    @XmlElement(required = true)
    protected String supportLevel;
    @XmlElement(required = true)
    protected int analysisFailureCases;
    @XmlElement(required = true)
    protected int analysisNormalCases;
    @XmlElement(required = true)
    protected String dateRange;
    @XmlElement(required = true)
    protected String filterFlag;
    @XmlElement(required = true)
    protected String failureType;
    @XmlElement(required = true)
    protected String dataFilter;
    protected int daysAfterEvent;
    @XmlElement(required = true)
    protected String algorithmSelection;
    @XmlElement(required = true)
    protected int coverageAnalysis;
    @XmlElement(required = true)
    protected String classification;
    @XmlElement(required = true)
    protected String rootCause;
    @XmlElement(required = true)
    protected String symptoms;
    @XmlElement(required = true)
    protected int feAssets;
    @XmlElement(required = true)
    protected int seAssets;
    @XmlElement(required = true)
    protected int normalSegments;
    @XmlElement(required = true)
    protected int failureSegments;
    @XmlElement(required = true)
    protected int totAssetsAnalysed;
    @XmlElement(required = true)
    protected String ruleMiningStartDate;
    @XmlElement(required = true)
    protected String ruleMiningEndDate;
    protected String faultCode;
    protected String runAgainst;
    private String rxDesc;

    /**
     * Gets the value of the baseDataResponseType property.
     * 
     * @return possible object is {@link BaseDataResponseType }
     * 
     */
    public BaseDataResponseType getBaseDataResponseType() {
        return baseDataResponseType;
    }

    /**
     * Sets the value of the baseDataResponseType property.
     * 
     * @param value
     *            allowed object is {@link BaseDataResponseType }
     * 
     */
    public void setBaseDataResponseType(BaseDataResponseType value) {
        this.baseDataResponseType = value;
    }

    /**
     * Gets the value of the segmentWindow property.
     * 
     */
    public int getSegmentWindow() {
        return segmentWindow;
    }

    /**
     * Sets the value of the segmentWindow property.
     * 
     */
    public void setSegmentWindow(int value) {
        this.segmentWindow = value;
    }

    /**
     * Gets the value of the classificationWindow property.
     * 
     */
    public int getClassificationWindow() {
        return classificationWindow;
    }

    /**
     * Sets the value of the classificationWindow property.
     * 
     */
    public void setClassificationWindow(int value) {
        this.classificationWindow = value;
    }

    /**
     * Gets the value of the classificationStepSize property.
     * 
     */
    public int getClassificationStepSize() {
        return classificationStepSize;
    }

    /**
     * Sets the value of the classificationStepSize property.
     * 
     */
    public void setClassificationStepSize(int value) {
        this.classificationStepSize = value;
    }

    /**
     * Gets the value of the progExclude property.
     * 
     */
    public int getProgExclude() {
        return progExclude;
    }

    /**
     * Sets the value of the progExclude property.
     * 
     */
    public void setProgExclude(int value) {
        this.progExclude = value;
    }

    /**
     * Gets the value of the normalCondition property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNormalCondition() {
        return normalCondition;
    }

    /**
     * Sets the value of the normalCondition property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNormalCondition(String value) {
        this.normalCondition = value;
    }

    /**
     * Gets the value of the supportLevel property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSupportLevel() {
        return supportLevel;
    }

    /**
     * Sets the value of the supportLevel property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSupportLevel(String value) {
        this.supportLevel = value;
    }

    /**
     * Gets the value of the analysisFailureCases property.
     * 
     */
    public int getAnalysisFailureCases() {
        return analysisFailureCases;
    }

    /**
     * Sets the value of the analysisFailureCases property.
     * 
     */
    public void setAnalysisFailureCases(int value) {
        this.analysisFailureCases = value;
    }

    /**
     * Gets the value of the analysisNormalCases property.
     * 
     */
    public int getAnalysisNormalCases() {
        return analysisNormalCases;
    }

    /**
     * Sets the value of the analysisNormalCases property.
     * 
     */
    public void setAnalysisNormalCases(int value) {
        this.analysisNormalCases = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDateRange(String value) {
        this.dateRange = value;
    }

    /**
     * Gets the value of the filterFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFilterFlag() {
        return filterFlag;
    }

    /**
     * Sets the value of the filterFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFilterFlag(String value) {
        this.filterFlag = value;
    }

    /**
     * Gets the value of the failureType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFailureType() {
        return failureType;
    }

    /**
     * Sets the value of the failureType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFailureType(String value) {
        this.failureType = value;
    }

    /**
     * Gets the value of the dataFilter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataFilter() {
        return dataFilter;
    }

    /**
     * Sets the value of the dataFilter property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDataFilter(String value) {
        this.dataFilter = value;
    }

    /**
     * Gets the value of the daysAfterEvent property.
     * 
     */
    public int getDaysAfterEvent() {
        return daysAfterEvent;
    }

    /**
     * Sets the value of the daysAfterEvent property.
     * 
     */
    public void setDaysAfterEvent(int value) {
        this.daysAfterEvent = value;
    }

    /**
     * Gets the value of the algorithmSelection property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAlgorithmSelection() {
        return algorithmSelection;
    }

    /**
     * Sets the value of the algorithmSelection property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAlgorithmSelection(String value) {
        this.algorithmSelection = value;
    }

    /**
     * Gets the value of the coverageAnalysis property.
     * 
     */
    public int getCoverageAnalysis() {
        return coverageAnalysis;
    }

    /**
     * Sets the value of the coverageAnalysis property.
     * 
     */
    public void setCoverageAnalysis(int value) {
        this.coverageAnalysis = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the rootCause property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRootCause() {
        return rootCause;
    }

    /**
     * Sets the value of the rootCause property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRootCause(String value) {
        this.rootCause = value;
    }

    /**
     * Gets the value of the symptoms property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSymptoms() {
        return symptoms;
    }

    /**
     * Sets the value of the symptoms property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSymptoms(String value) {
        this.symptoms = value;
    }

    /**
     * Gets the value of the feAssets property.
     * 
     */
    public int getFeAssets() {
        return feAssets;
    }

    /**
     * Sets the value of the feAssets property.
     * 
     */
    public void setFeAssets(int value) {
        this.feAssets = value;
    }

    /**
     * Gets the value of the seAssets property.
     * 
     */
    public int getSeAssets() {
        return seAssets;
    }

    /**
     * Sets the value of the seAssets property.
     * 
     */
    public void setSeAssets(int value) {
        this.seAssets = value;
    }

    /**
     * Gets the value of the normalSegments property.
     * 
     */
    public int getNormalSegments() {
        return normalSegments;
    }

    /**
     * Sets the value of the normalSegments property.
     * 
     */
    public void setNormalSegments(int value) {
        this.normalSegments = value;
    }

    /**
     * Gets the value of the failureSegments property.
     * 
     */
    public int getFailureSegments() {
        return failureSegments;
    }

    /**
     * Sets the value of the failureSegments property.
     * 
     */
    public void setFailureSegments(int value) {
        this.failureSegments = value;
    }

    /**
     * Gets the value of the totAssetsAnalysed property.
     * 
     */
    public int getTotAssetsAnalysed() {
        return totAssetsAnalysed;
    }

    /**
     * Sets the value of the totAssetsAnalysed property.
     * 
     */
    public void setTotAssetsAnalysed(int value) {
        this.totAssetsAnalysed = value;
    }

    /**
     * Gets the value of the ruleMiningStartDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleMiningStartDate() {
        return ruleMiningStartDate;
    }

    /**
     * Sets the value of the ruleMiningStartDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleMiningStartDate(String value) {
        this.ruleMiningStartDate = value;
    }

    /**
     * Gets the value of the ruleMiningEndDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleMiningEndDate() {
        return ruleMiningEndDate;
    }

    /**
     * Sets the value of the ruleMiningEndDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleMiningEndDate(String value) {
        this.ruleMiningEndDate = value;
    }

    /**
     * Gets the value of the faultCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFaultCode() {
        return faultCode;
    }

    /**
     * Sets the value of the faultCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFaultCode(String value) {
        this.faultCode = value;
    }

    /**
     * Gets the value of the runAgainst property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRunAgainst() {
        return runAgainst;
    }

    /**
     * Sets the value of the runAgainst property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRunAgainst(String value) {
        this.runAgainst = value;
    }

    /**
     * @return the rxDesc
     */
    public String getRxDesc() {
        return rxDesc;
    }

    /**
     * @param rxDesc
     *            the rxDesc to set
     */
    public void setRxDesc(String rxDesc) {
        this.rxDesc = rxDesc;
    }

}
