//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-04/09/2009 09:05 AM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 12:55:50 AM IST 
//

package com.ge.trans.rmd.services.kep.knowledgeseeker.valueobjects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for trackingSummaryResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="trackingSummaryResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="summaryDataResponseType" type="{http://omd/omdservices/knowledgeSeekerService}summaryDataResponseType" maxOccurs="unbounded"/>
 *         &lt;element name="analysisDataResponseType" type="{http://omd/omdservices/knowledgeSeekerService}analysisDataResponseType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trackingSummaryResponseType", propOrder = { "summaryDataResponseType", "analysisDataResponseType" })
@XmlRootElement
public class TrackingSummaryResponseType {

    @XmlElement(required = true)
    protected List<SummaryDataResponseType> summaryDataResponseType;
    @XmlElement(required = true)
    protected List<AnalysisDataResponseType> analysisDataResponseType;

    /**
     * Gets the value of the summaryDataResponseType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the summaryDataResponseType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSummaryDataResponseType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SummaryDataResponseType }
     * 
     * 
     */
    public List<SummaryDataResponseType> getSummaryDataResponseType() {
        if (summaryDataResponseType == null) {
            summaryDataResponseType = new ArrayList<SummaryDataResponseType>();
        }
        return this.summaryDataResponseType;
    }

    /**
     * Gets the value of the analysisDataResponseType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the analysisDataResponseType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAnalysisDataResponseType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnalysisDataResponseType }
     * 
     * 
     */
    public List<AnalysisDataResponseType> getAnalysisDataResponseType() {
        if (analysisDataResponseType == null) {
            analysisDataResponseType = new ArrayList<AnalysisDataResponseType>();
        }
        return this.analysisDataResponseType;
    }

}
